#define F(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
};
#define JIP(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
    jip = 1; \
};

#define ANYONE 0
#define CLIENT 1
#define SERVER 2
#define HC HC_Life

class CfgRemoteExec {
    class Functions {
        mode = 1;
        jip = 0;
        
        /* Client only functions */
        F(ALSG_fnc_AAN,CLIENT)
        F(ALSG_fnc_AANBank,CLIENT)
        F(ALSG_fnc_addVehicle2Chain,CLIENT)
        F(ALSG_fnc_adminID,CLIENT)
        F(ALSG_fnc_adminInfo,CLIENT)
        F(ALSG_fnc_bountyReceive,CLIENT)
        F(ALSG_fnc_copSearch,CLIENT)
        JIP(ALSG_fnc_copSiren,CLIENT)
        F(ALSG_fnc_freezePlayer,CLIENT)
        F(ALSG_fnc_gangDisbanded,CLIENT)
        F(ALSG_fnc_gangInvite,CLIENT)
        F(ALSG_fnc_garageRefund,CLIENT)
        F(ALSG_fnc_giveDiff,CLIENT)
        F(ALSG_fnc_hideObj,CLIENT)
        F(ALSG_fnc_impoundMenu,CLIENT)
        F(ALSG_fnc_jail,CLIENT)
        F(ALSG_fnc_jailMe,CLIENT)
        F(ALSG_fnc_knockedOut,CLIENT)
        F(ALSG_fnc_licenseCheck,CLIENT)
        F(ALSG_fnc_licensesRead,CLIENT)
        F(ALSG_fnc_lightHouse,CLIENT)
        F(ALSG_fnc_medicRequest,CLIENT)
        JIP(ALSG_fnc_medicSiren,CLIENT)
        F(ALSG_fnc_moveIn,CLIENT)
        F(ALSG_fnc_pickupItem,CLIENT)
        F(ALSG_fnc_pickupMoney,CLIENT)
        F(ALSG_fnc_removeLicenses,CLIENT)
        F(ALSG_fnc_restrain,CLIENT)
        F(ALSG_fnc_revived,CLIENT)
        F(ALSG_fnc_robPerson,CLIENT)
        F(ALSG_fnc_robReceive,CLIENT)
        F(ALSG_fnc_searchClient,CLIENT)
        F(ALSG_fnc_seizeClient,CLIENT)
        F(ALSG_fnc_spikeStripEffect,CLIENT)
        F(ALSG_fnc_tazeSound,CLIENT)
        F(ALSG_fnc_ticketPrompt,CLIENT)
        F(ALSG_fnc_vehicleAnimate,CLIENT)
        F(ALSG_fnc_wireTransfer,CLIENT)
        F(ALSG_fnc_dataQuery,CLIENT)
        F(ALSG_fnc_insertPlayerInfo,CLIENT)
        F(ALSG_fnc_requestReceived,CLIENT)
        F(ALSG_fnc_updateRequest,CLIENT)
        F(TON_fnc_clientGangKick,CLIENT)
        F(TON_fnc_clientGangLeader,CLIENT)
        F(TON_fnc_clientGangLeft,CLIENT)
        F(TON_fnc_clientGetKey,CLIENT)
        F(TON_fnc_clientMessage,CLIENT)
        F(TON_fnc_player_query,CLIENT)
        F(ALSG_fnc_killfeed,CLIENT)
        F(ALSG_fnc_radArea,CLIENT)
        F(ALSG_fnc_cprrevived,CLIENT)
        F(ALSG_fnc_tieing,CLIENT)
		F(ALSG_fnc_tieingb,CLIENT)
		F(ALSG_fnc_gagged,CLIENT)
        F(ALSG_fnc_backupCall,CLIENT)
        F(ALSG_fnc_removeWeaponAction,CLIENT)
        F(ALSG_fnc_GangCreated,CLIENT)
        F(ALSG_fnc_writeDeathScreen, CLIENT)
        F(ALSG_fnc_giveItemReturn,CLIENT)
        F(ALSG_fnc_receiveitem,CLIENT)
        F(ArmaLife_PropertyTaxPay,CLIENT)
        F(ArmaLife_BuyTicket,CLIENT)
        F(ArmaLife_TazedGangPerk,CLIENT)
        F(ArmaLife_KillHostage,CLIENT)
        F(ALSG_fnc_receiveWarrants,CLIENT)
        F(ArmaLife_GetSetName,CLIENT)
        F(ArmaLife_SaveName,CLIENT)
        F(ArmaLife_PlayerStabilized,CLIENT)
        F(ArmaLife_DenyFee,CLIENT)
        F(ArmaLife_AC_Bank,CLIENT)
        F(ALSG_fnc_contactCheck,CLIENT)
        F(AH_PlayerLoad,CLIENT)

        /* Server only functions */
        F(AH_LogInterface, SERVER)
        F(ALSG_fnc_insertRequest,SERVER)
        F(ALSG_fnc_queryRequest,SERVER)
        F(ALSG_fnc_updatePartialServer,SERVER)
        F(ALSG_fnc_updateRequestServer,SERVER)
        F(ALSG_fnc_jailSys,SERVER)
        F(TON_fnc_addContainer,SERVER)
        F(TON_fnc_addHouse,SERVER)
        F(TON_fnc_chopShopSell,SERVER)
        F(TON_fnc_cleanupRequest,SERVER)
        F(TON_fnc_deleteDBContainer,SERVER)
        F(TON_fnc_getID,SERVER)
        F(TON_fnc_getVehicles,SERVER)
        F(TON_fnc_insureVehicle,SERVER)
        F(TON_fnc_insertGang,SERVER)
        F(TON_fnc_keyManagement,SERVER)
        F(TON_fnc_pickupAction,SERVER)
        F(TON_fnc_removeGang,SERVER)
        F(TON_fnc_sellHouse,SERVER)
        F(TON_fnc_sellHouseContainer,SERVER)
        F(TON_fnc_spawnVehicle,SERVER)
        F(TON_fnc_spikeStrip,SERVER)
        F(TON_fnc_updateGang,SERVER)
        F(TON_fnc_updateHouseContainers,SERVER)
        F(TON_fnc_updateHouseTrunk,SERVER)
        F(TON_fnc_vehicleCreate,SERVER)
        F(TON_fnc_vehicleDelete,SERVER)
        F(TON_fnc_vehicleStore,SERVER)
        F(TON_fnc_vehicleUpdate,SERVER)
        F(TON_fnc_houseGarage,SERVER)
        F(TON_fnc_insureCar,SERVER) 
        F(serverVehicleStore,SERVER)
        F(ALSG_fnc_addWarrantsServ,SERVER)
        F(ALSG_fnc_delWarrantsServ,SERVER)
        F(ALSG_fnc_queryWarrantsServ,SERVER)
        F(ALSG_fnc_jailSaveTime,SERVER)
        F(ArmaLife_ImpoundVehicleServ,SERVER)
        F(ArmaLife_UpdateLevel,SERVER)
        F(ArmaLife_PropertyTaxCheck,SERVER)
        F(ArmaLife_PropertyTaxPayServ,SERVER)
        F(ArmaLife_PropertyTaxCheckLogin,SERVER)
        F(ArmaLife_WealthTaxCheckLogin,SERVER)
        F(ArmaLife_CheckTick,SERVER)
        F(ArmaLife_BuyTicketServ,SERVER)
        F(ArmaLife_UnlockTask,SERVER)
        F(ArmaLife_Lib_CreateMarker,SERVER)
        F(ArmaLife_Lib_ChangeGangMarker,SERVER)
        F(ArmaLife_AC_SetDamage,SERVER)
        F(ArmaLife_AC_SetDamageObject,SERVER)
        F(ArmaLife_AC_OpenTrunk,SERVER)
        F(ArmaLife_AC_CloseTrunk,SERVER)
        F(ArmaLife_ReciveGangProfit,SERVER)
        F(ArmaLife_HandleCharge,SERVER)
        F(ArmaLife_PlaceItem,SERVER)
        F(ArmaLife_ItemBought,SERVER)
        F(ArmaLife_TotalItems,SERVER)
        F(AH_KeyCheck,SERVER)
        F(ArmaLife_Lib_ChangeGangMarkerColor,SERVER)
        JIP(mav_ttm_fnc_loadFromDatabase,SERVER)
        JIP(mav_ttm_fnc_updateDatabaseEntry,SERVER)

        /* Functions for everyone */
        F(BIS_fnc_effectKilledAirDestruction,ANYONE)
        F(BIS_fnc_effectKilledSecondaries,ANYONE)
        F(ALSG_fnc_animSync,ANYONE)
        F(ALSG_fnc_broadcast,ANYONE)
        F(ALSG_fnc_colorVehicle,ANYONE)
        F(ALSG_fnc_flashbang,ANYONE)
        F(ALSG_fnc_lockVehicle,ANYONE)
        F(ALSG_fnc_pulloutVeh,ANYONE)
        F(ALSG_fnc_setFuel,ANYONE)
        F(ALSG_fnc_simDisable,ANYONE)
        F(SPY_fnc_notifyAdmins,ANYONE)
        F(ALSG_fnc_setEngineHit,ANYONE)
        F(ALSG_fnc_notificationSystem,ANYONE)
        F(ALSG_fnc_hudUpdate,ANYONE)
        F(ALSG_fnc_crashTackled,ANYONE)   
        F(ALSG_fnc_GangInviteReceived,ANYONE)
        F(ALSG_fnc_GangNewLeader,ANYONE)
        F(ALSG_fnc_loadGangMenu,ANYONE)
        F(ALSG_fnc_getKey,ANYONE)
        F(ALSG_fnc_ReceiveMoney,ANYONE)
        F(ALSG_fnc_SetupQueryNumber,ANYONE)
        F(ALSG_fnc_Server_MessageRelay,ANYONE)
        F(ALSG_fnc_ReceiveEMessage, ANYONE)
        F(ArmaLife_NotifyCheckpoint, ANYONE)
    };

    class Commands {
        mode = 1;
        jip = 0;

        F(setunitloadout,CLIENT)
        F(addHandgunItem,ANYONE)
        F(addMagazine,ANYONE)
        F(addPrimaryWeaponItem,ANYONE)
        F(addWeapon,ANYONE)
        F(setFuel,ANYONE)
        F(playSound,CLIENT)
        F(say3D,CLIENT)
        F(hideobjectglobal,ANYONE)
    };
};
