/*
    Master UI Resource File
*/
#include "common.hpp"
#include "common1.hpp"
#include "chop_shop.hpp"
#include "vehicleShop.hpp"
#include "FuelStat.hpp"

//Arma-Life Dialogs
#include "AH_Dialog.hpp"
#include "ArmaLife_Controls.hpp"
#include "ArmaLife_PhoneControls.hpp"
#include "ArmaLife_Bank.hpp"
#include "ArmaLife_CheckpointBuilder.hpp"
#include "ArmaLife_Interaction.hpp"
#include "ArmaLife_DMVTest.hpp"
#include "ArmaLife_Phone.hpp"
#include "ArmaLife_ThreatLevel.hpp"
#include "ArmaLife_SpawnMenu.hpp"
#include "ArmaLife_VIPNametag.hpp"
#include "ArmaLife_PickupMenu.hpp"
#include "ArmaLife_Deathscreen.hpp"
#include "ArmaLife_Garage.hpp"
#include "ArmaLife_Whitelist.hpp"
#include "ArmaLife_ImpoundLot.hpp"
#include "ArmaLife_JobMenu.hpp"
#include "ArmaLife_Hud.hpp"
#include "ArmaLife_GangProgress.hpp"
#include "ArmaLife_Ticket.hpp"
#include "ArmaLife_Loading.hpp"
#include "ArmaLife_EquipmentShop.hpp"
#include "ArmaLife_Warrents.hpp"
#include "ArmaLife_JailHud.hpp"
#include "ArmaLife_JailTime.hpp"
#include "ArmaLife_SetName.hpp"
#include "ArmaLife_GangMenu.hpp"
#include "ArmaLife_ItemShop.hpp"
#include "ArmaLife_VehicleInventory.hpp"
#include "ArmaLife_ClothingShop.hpp"
#include "ArmaLife_MarkerMenu.hpp"
#include "ArmaLife_VehicleShop.hpp"