/*
*    ARRAY FORMAT:
*        0: STRING (Classname)
*        1: STRING (Display Name, leave as "" for default)
*        2: SCALAR (Price)
*        3: STRING (Conditions) - Must return boolean :
*            String can contain any amount of conditions, aslong as the entire
*            string returns a boolean. This allows you to check any levels, licenses etc,
*            in any combination. For example:
*                "call life_coplevel && license_civ_someLicense"
*            This will also let you call any other function.
*
*   Clothing classnames can be found here: https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Equipment
*   Backpacks/remaining classnames can be found here (TIP: Search page for "pack"): https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EMPTY
*
*/
class Clothing {
    class bruce {
        title = "STR_Shops_C_Bruce";
        conditions = "";
        side = "";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "travis_polocookiemonster", "", 30, "" },
            { "U_B_Protagonist_VR", "Admin Suit", 30, "(call life_adminlevel) > 0 " },
            { "travis_poloapple", "", 30, "" },
            { "travis_polohellokitty", "", 30, "" },
            { "travis_polohellokitty1", "", 30, "" },
            { "travis_timmac", "", 30, "" },
            { "travis_Butts", "", 30, "" },
            { "travis_poloaustralia", "", 30, "" },
            { "travis_polospongebob", "", 30, "" },
            { "travis_polopatrickstar", "", 30, "" },
            { "travis_polocanda", "", 30, "" },
            { "travis_pololove", "", 30, "" },
            { "travis_polofuck", "", 30, "" },
            { "travis_polococacola", "", 30, "" },
            { "travis_poloangelo", "", 30, "" },
            { "travis_polomrbong", "", 30, "" },
            { "travis_polomoon", "", 30, "" },
            { "travis_polodino", "", 30, "" },
            { "travis_polostunt", "", 30, "" },
            { "travis_poloface", "", 30, "" },
            { "travis_avengers", "", 30, "" },
            { "travis_doge", "", 30, "" },
            { "travis_fuckit", "", 30, "" },
            { "travis_illuminati", "", 30, "" },
            { "travis_jeff", "", 30, "" },
            { "travis_kappa", "", 30, "" },
            { "travis_married", "", 30, "" },
            { "travis_marvel", "", 30, "" },
            { "travis_mexicantroll", "", 30, "" },
            { "travis_minion", "", 30, "" },
            { "travis_monstercat", "", 30, "" },
            { "travis_nike", "", 30, "" },
            { "travis_pancake", "", 30, "" },
            { "travis_shield", "", 30, "" },
            { "travis_smile", "", 30, "" },
            { "travis_Batman", "", 30, "" },
            { "travis_tux", "", 30, "" },
            { "travis_twitch", "", 30, "" },
            { "travis_yaoming", "", 30, "" },
            { "travis_smokeweed", "", 30, "" },
            { "travis_Snoopy", "", 30, "" },
            { "travis_Coco", "", 30, "" },
            { "travis_Ciggy", "", 30, "" },
            { "travis_Adidas", "", 30, "" },
            { "kojixus_wolf", "", 30, "" },
            { "kojixus_picklerick", "", 30, "" },
            { "kojixus_russianpepe", "", 30, "" },
            { "kojixus_angrypepe", "", 30, "" },
            { "kojixus_trippieredd", "", 30, "" },
            { "kojixus_mexicanfarmer", "", 30, "" },
            { "kojixus_xxxtenaction", "", 30, "" },
            { "travis_polopsisyndicate", "", 30, "" },
            { "kojixus_psiblack", "", 30, "" },
            { "kojixus_psi", "", 30, "" },
            { "kojixus_wizard", "", 30, "" },
            { "kojixus_vapenation", "", 30, "" },
            { "kojixus_supreme", "", 30, "" },
            { "kojixus_treyway", "", 30, "" },
            {"d3s_uniform_jbib_008_a", "", 30, ""},
            {"d3s_uniform_jbib_008_aa", "", 30, ""},
            {"d3s_uniform_jbib_008_ab", "", 30, ""},
            {"d3s_uniform_jbib_008_ac", "", 30, ""},
            {"d3s_uniform_jbib_008_ad", "", 30, ""},
            {"d3s_uniform_jbib_008_ae", "", 30, ""},
            {"d3s_uniform_jbib_008_af", "", 30, ""},
            {"d3s_uniform_jbib_008_b", "", 30, ""},
            {"d3s_uniform_jbib_008_ba", "", 30, ""},
            {"d3s_uniform_jbib_008_bb", "", 30, ""},
            {"d3s_uniform_jbib_008_bc", "", 30, ""},
            {"d3s_uniform_jbib_008_bd", "", 30, ""},
            {"d3s_uniform_jbib_008_be", "", 30, ""},
            {"d3s_uniform_jbib_008_bf", "", 30, ""},
            {"d3s_uniform_jbib_008_c", "", 30, ""},
            {"d3s_uniform_jbib_008_ca", "", 30, ""},
            {"d3s_uniform_jbib_008_cb", "", 30, ""},
            {"d3s_uniform_jbib_008_cc", "", 30, ""},
            {"d3s_uniform_jbib_008_cd", "", 30, ""},
            {"d3s_uniform_jbib_008_ce", "", 30, ""},
            {"d3s_uniform_jbib_008_cf", "", 30, ""},
            {"d3s_uniform_jbib_008_d", "", 30, ""},
            {"d3s_uniform_jbib_008_da", "", 30, ""},
            {"d3s_uniform_jbib_008_db", "", 30, ""},
            {"d3s_uniform_jbib_008_dc", "", 30, ""},
            {"d3s_uniform_jbib_008_dd", "", 30, ""},
            {"d3s_uniform_jbib_008_de", "", 30, ""},
            {"d3s_uniform_jbib_008_df", "", 30, ""},
            {"d3s_uniform_jbib_008_e", "", 30, ""},
            {"d3s_uniform_jbib_008_ea", "", 30, ""},
            {"d3s_uniform_jbib_008_eb", "", 30, ""},
            {"d3s_uniform_jbib_008_ec", "", 30, ""},
            {"d3s_uniform_jbib_008_ed", "", 30, ""},
            {"d3s_uniform_jbib_008_ee", "", 30, ""},
            {"d3s_uniform_jbib_008_ef", "", 30, ""},
            {"d3s_uniform_jbib_008_f", "", 30, ""},
            {"d3s_uniform_jbib_008_fa", "", 30, ""},
            {"d3s_uniform_jbib_008_fb", "", 30, ""},
            {"d3s_uniform_jbib_008_fc", "", 30, ""},
            {"d3s_uniform_jbib_008_fd", "", 30, ""},
            {"d3s_uniform_jbib_008_fe", "", 30, ""},
            {"d3s_uniform_jbib_008_ff", "", 30, ""},
            {"d3s_uniform_jbib_008_g", "", 30, ""},
            {"d3s_uniform_jbib_008_ga", "", 30, ""},
            {"d3s_uniform_jbib_008_gb", "", 30, ""},
            {"d3s_uniform_jbib_008_gc", "", 30, ""},
            {"d3s_uniform_jbib_008_gd", "", 30, ""},
            {"d3s_uniform_jbib_008_ge", "", 30, ""},
            {"d3s_uniform_jbib_008_gf", "", 30, ""},
            {"d3s_uniform_jbib_008_h", "", 30, ""},
            {"d3s_uniform_jbib_008_ha", "", 30, ""},
            {"d3s_uniform_jbib_008_hb", "", 30, ""},
            {"d3s_uniform_jbib_008_hc", "", 30, ""},
            {"d3s_uniform_jbib_008_hd", "", 30, ""},
            {"d3s_uniform_jbib_008_he", "", 30, ""},
            {"d3s_uniform_jbib_008_hf", "", 30, ""},
            {"d3s_uniform_jbib_008_i", "", 30, ""},
            {"d3s_uniform_jbib_008_ia", "", 30, ""},
            {"d3s_uniform_jbib_008_ib", "", 30, ""},
            {"d3s_uniform_jbib_008_ic", "", 30, ""},
            {"d3s_uniform_jbib_008_id", "", 30, ""},
            {"d3s_uniform_jbib_008_ie", "", 30, ""},
            {"d3s_uniform_jbib_008_if", "", 30, ""},
            {"d3s_uniform_jbib_008_j", "", 30, ""},
            {"d3s_uniform_jbib_008_ja", "", 30, ""},
            {"d3s_uniform_jbib_008_jb", "", 30, ""},
            {"d3s_uniform_jbib_008_jc", "", 30, ""},
            {"d3s_uniform_jbib_008_jd", "", 30, ""},
            {"d3s_uniform_jbib_008_je", "", 30, ""},
            {"d3s_uniform_jbib_008_jf", "", 30, ""},
            {"d3s_uniform_jbib_008_k", "", 30, ""},
            {"d3s_uniform_jbib_008_ka", "", 30, ""},
            {"d3s_uniform_jbib_008_kb", "", 30, ""},
            {"d3s_uniform_jbib_008_kc", "", 30, ""},
            {"d3s_uniform_jbib_008_kd", "", 30, ""},
            {"d3s_uniform_jbib_008_ke", "", 30, ""},
            {"d3s_uniform_jbib_008_kf", "", 30, ""},
            {"d3s_uniform_jbib_008_l", "", 30, ""},
            {"d3s_uniform_jbib_008_la", "", 30, ""},
            {"d3s_uniform_jbib_008_lb", "", 30, ""},
            {"d3s_uniform_jbib_008_lc", "", 30, ""},
            {"d3s_uniform_jbib_008_ld", "", 30, ""},
            {"d3s_uniform_jbib_008_le", "", 30, ""},
            {"d3s_uniform_jbib_008_lf", "", 30, ""},
            {"d3s_uniform_jbib_008_m", "", 30, ""},
            {"d3s_uniform_jbib_008_ma", "", 30, ""},
            {"d3s_uniform_jbib_008_mb", "", 30, ""},
            {"d3s_uniform_jbib_008_mc", "", 30, ""},
            {"d3s_uniform_jbib_008_md", "", 30, ""},
            {"d3s_uniform_jbib_008_me", "", 30, ""},
            {"d3s_uniform_jbib_008_mf", "", 30, ""},
            {"d3s_uniform_jbib_008_n", "", 30, ""},
            {"d3s_uniform_jbib_008_na", "", 30, ""},
            {"d3s_uniform_jbib_008_nb", "", 30, ""},
            {"d3s_uniform_jbib_008_nc", "", 30, ""},
            {"d3s_uniform_jbib_008_nd", "", 30, ""},
            {"d3s_uniform_jbib_008_ne", "", 30, ""},
            {"d3s_uniform_jbib_008_nf", "", 30, ""},
            {"d3s_uniform_jbib_008_o", "", 30, ""},
            {"d3s_uniform_jbib_008_oa", "", 30, ""},
            {"d3s_uniform_jbib_008_ob", "", 30, ""},
            {"d3s_uniform_jbib_008_oc", "", 30, ""},
            {"d3s_uniform_jbib_008_od", "", 30, ""},
            {"d3s_uniform_jbib_008_oe", "", 30, ""},
            {"d3s_uniform_jbib_008_of", "", 30, ""},
            {"U_NikosAgedBody", "", 30, ""},
            {"TRYK_SUITS_BLK_F", "", 30, ""},
            {"TRYK_SUITS_BR_F", "", 30, ""}

        };

        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },

            { "H_RacingHelmet_1_black_F", "", 100, "" },
            { "H_RacingHelmet_1_red_F", "", 100, "" },
            { "H_RacingHelmet_1_white_F", "", 100, "" },
            { "H_RacingHelmet_1_blue_F", "", 100, "" },
            { "H_RacingHelmet_1_yellow_F", "", 100, "" },
            { "H_RacingHelmet_1_green_F", "", 100, "" },
            { "H_RacingHelmet_1_F", "", 200, "" },
            { "H_RacingHelmet_2_F", "", 200, "" },
            { "H_RacingHelmet_3_F", "", 200, "" },
            { "H_RacingHelmet_4_F", "", 200, "" },
            
            {"d3s_CAP_christmas_head_a", "", 30, ""},
            {"d3s_CAP_christmas_head_b", "", 30, ""},
            {"d3s_CAP_christmas_head_c", "", 30, ""},
            {"d3s_CAP_christmas_head_d", "", 30, ""},
            {"d3s_CAP_christmas_head_e", "", 30, ""},
            {"d3s_CAP_christmas_head_f", "", 30, ""},
            {"d3s_CAP_christmas_head_g", "", 30, ""},
            {"d3s_CAP_christmas_head_h", "", 30, ""},
            {"d3s_CAP_christmas_head1", "", 30, ""},
            {"d3s_CAP_christmas_head2_a", "", 30, ""},
            {"d3s_CAP_christmas_head2_b", "", 30, ""},
            {"d3s_CAP_christmas_head2_c", "", 30, ""},
            {"d3s_CAP_christmas_head2_d", "", 30, ""},
            {"d3s_CAP_christmas_head3_a", "", 30, ""},
            {"d3s_CAP_christmas_head3_b", "", 30, ""},
            {"d3s_CAP_christmas_head3_c", "", 30, ""},
            {"d3s_CAP_christmas_head3_d", "", 30, ""},
            {"d3s_CAP_christmas_head4_a", "", 30, ""},
            {"d3s_CAP_christmas_head4_b", "", 30, ""},
            {"d3s_CAP_christmas_head4_c", "", 30, ""},
            {"d3s_CAP_christmas_head4_d", "", 30, ""},
            {"d3s_CAP_christmas_head4_e", "", 30, ""},
            {"d3s_CAP_christmas_head4_f", "", 30, ""},
            {"d3s_CAP_christmas_head4_g", "", 30, ""},
            {"d3s_CAP_christmas_head4_h", "", 30, ""},
            {"d3s_CAP_christmas_head5_a", "", 30, ""},
            {"d3s_CAP_christmas_head5_b", "", 30, ""},
            {"d3s_CAP_christmas_head5_c", "", 30, ""},
            {"d3s_CAP_christmas_head5_d", "", 30, ""},
            {"d3s_CAP_christmas_head5_e", "", 30, ""},
            {"d3s_CAP_christmas_head5_f", "", 30, ""},
            {"d3s_CAP_christmas_head5_g", "", 30, ""},
            {"d3s_CAP_christmas_head5_h", "", 30, ""},
            {"d3s_CAP_p_head_000_a", "", 30, ""},
            {"d3s_CAP_p_head_000_b", "", 30, ""},
            {"d3s_CAP_p_head_000_c", "", 30, ""},
            {"d3s_CAP_p_head_000_d", "", 30, ""},
            {"d3s_CAP_p_head_000_e", "", 30, ""},
            {"d3s_CAP_p_head_000_f", "", 30, ""},
            {"d3s_CAP_p_head_000_g", "", 30, ""},
            {"d3s_CAP_p_head_000_h", "", 30, ""},
            {"d3s_CAP_p_head_000_i", "", 30, ""},
            {"d3s_CAP_p_head_000_j", "", 30, ""},
            {"d3s_CAP_p_head_000_k", "", 30, ""},
            {"d3s_CAP_p_head_000_l", "", 30, ""},
            {"d3s_CAP_p_head_000_m", "", 30, ""},
            {"d3s_CAP_p_head_000_n", "", 30, ""},
            {"d3s_CAP_p_head_000_o", "", 30, ""},
            {"d3s_CAP_p_head_000_p", "", 30, ""},
            {"d3s_CAP_p_head_000_q", "", 30, ""},
            {"d3s_CAP_p_head_000_r", "", 30, ""},
            {"d3s_CAP_p_head_000_s", "", 30, ""},
            {"d3s_CAP_p_head_000_t", "", 30, ""},
            {"d3s_CAP_p_head_001_a", "", 30, ""},
            {"d3s_CAP_p_head_001_b", "", 30, ""},
            {"d3s_CAP_p_head_001_c", "", 30, ""},
            {"d3s_CAP_p_head_001_d", "", 30, ""},
            {"d3s_CAP_p_head_001_e", "", 30, ""},
            {"d3s_CAP_p_head_001_f", "", 30, ""},
            {"d3s_CAP_p_head_001_g", "", 30, ""},
            {"d3s_CAP_p_head_001_h", "", 30, ""},
            {"d3s_CAP_p_head_001_i", "", 30, ""},
            {"d3s_CAP_p_head_001_j", "", 30, ""},
            {"d3s_CAP_p_head_004_a", "", 30, ""},
            {"d3s_CAP_p_head_004_b", "", 30, ""},
            {"d3s_CAP_p_head_004_c", "", 30, ""},
            {"d3s_CAP_p_head_004_d", "", 30, ""},
            {"d3s_CAP_p_head_004_e", "", 30, ""},
            {"d3s_CAP_p_head_004_f", "", 30, ""},
            {"d3s_CAP_p_head_004_g", "", 30, ""},
            {"d3s_CAP_p_head_004_h", "", 30, ""},
            {"d3s_CAP_p_head_004_i", "", 30, ""},
            {"d3s_CAP_p_head_004_j", "", 30, ""},
            {"d3s_CAP_p_head_004_k", "", 30, ""},
            {"d3s_CAP_p_head_004_l", "", 30, ""},
            {"d3s_CAP_p_head_004_m", "", 30, ""},
            {"d3s_CAP_p_head_005_a", "", 30, ""},
            {"d3s_CAP_p_head_005_b", "", 30, ""},
            {"d3s_CAP_p_head_005_c", "", 30, ""},
            {"d3s_CAP_p_head_005_d", "", 30, ""},
            {"d3s_CAP_p_head_005_e", "", 30, ""},
            {"d3s_CAP_p_head_005_f", "", 30, ""},
            {"d3s_CAP_p_head_005_g", "", 30, ""},
            {"d3s_CAP_p_head_005_h", "", 30, ""},
            {"d3s_CAP_p_head_005_i", "", 30, ""},
            {"d3s_CAP_p_head_005_j", "", 30, ""},
            {"d3s_CAP_p_head_005_k", "", 30, ""},
            {"d3s_CAP_p_head_005_l", "", 30, ""},
            {"d3s_CAP_p_head_005_m", "", 30, ""},
            {"d3s_CAP_p_head_005_n", "", 30, ""},
            {"d3s_CAP_p_head_005_o", "", 30, ""},
            {"d3s_CAP_p_head_005_p", "", 30, ""},
            {"d3s_CAP_p_head_005_q", "", 30, ""},
            {"d3s_CAP_p_head_005_r", "", 30, ""},
            {"d3s_CAP_p_head_005_s", "", 30, ""},
            {"d3s_CAP_p_head_005_t", "", 30, ""},
            {"d3s_CAP_p_head_005_u", "", 30, ""},
            {"d3s_CAP_p_head_005_v", "", 30, ""},
            {"d3s_CAP_p_head_005_w", "", 30, ""},
            {"d3s_CAP_p_head_005_x", "", 30, ""},
            {"d3s_CAP_p_head_005_y", "", 30, ""},
            {"d3s_CAP_p_head_005_z", "", 30, ""},
            {"d3s_CAP_p_head_006_a", "", 30, ""},
            {"d3s_CAP_p_head_006_b", "", 30, ""},
            {"d3s_CAP_berd_000_u_a", "", 30, ""},
            {"d3s_CAP_berd_000_u_b", "", 30, ""},
            {"d3s_CAP_berd_000_u_c", "", 30, ""},
            {"d3s_CAP_berd_000_u_d", "", 30, ""},
            {"d3s_CAP_berd_000_u_e", "", 30, ""},
            {"d3s_CAP_berd_002_u_a", "", 30, ""},
            {"d3s_CAP_berd_002_u_b", "", 30, ""},
            {"d3s_CAP_berd_002_u_c", "", 30, ""},
            {"d3s_CAP_berd_002_u_d", "", 30, ""},
            {"d3s_CAP_berd_002_u_e", "", 30, ""},
            {"d3s_CAP_berd_002_u_f", "", 30, ""},
            {"d3s_CAP_berd_002_u_g", "", 30, ""},
            {"d3s_CAP_berd_002_u_h", "", 30, ""},
            {"d3s_CAP_berd_002_u_i", "", 30, ""},
            {"d3s_CAP_berd_002_u_j", "", 30, ""},
            {"d3s_CAP_berd_002_u_k", "", 30, ""},
            {"d3s_CAP_berd_002_u_l", "", 30, ""},
            {"d3s_CAP_berd_002_u_m", "", 30, ""},
            {"d3s_CAP_berd_002_u_n", "", 30, ""},
            {"d3s_CAP_berd_002_u_o", "", 30, ""},
            {"d3s_CAP_berd_002_u_p", "", 30, ""},
            {"d3s_CAP_berd_002_u_q", "", 30, ""},
            {"d3s_CAP_berd_002_u_r", "", 30, ""},
            {"d3s_CAP_berd_002_u_s", "", 30, ""},
            {"d3s_CAP_berd_002_u_t", "", 30, ""},
            {"d3s_CAP_berd_002_u_u", "", 30, ""},
            {"d3s_CAP_berd_002_u_v", "", 30, ""},
            {"d3s_CAP_berd_002_u_w", "", 30, ""},
            {"d3s_CAP_berd_002_u_x", "", 30, ""},
            {"d3s_CAP_berd_002_u_y", "", 30, ""},
            {"d3s_CAP_berd_002_u_z", "", 30, ""},
            {"d3s_CAP_berd_003_u_a", "", 30, ""},
            {"d3s_CAP_berd_003_u_b", "", 30, ""},
            {"d3s_CAP_berd_003_u_c", "", 30, ""},
            {"d3s_CAP_berd_003_u_d", "", 30, ""},
            {"d3s_CAP_berd_003_u_e", "", 30, ""},
            {"d3s_CAP_berd_003_u_f", "", 30, ""},
            {"d3s_CAP_berd_003_u_g", "", 30, ""},
            {"d3s_CAP_berd_003_u_h", "", 30, ""},
            {"d3s_CAP_berd_003_u_i", "", 30, ""},
            {"d3s_CAP_berd_003_u_j", "", 30, ""},
            {"d3s_CAP_berd_003_u_k", "", 30, ""},
            {"d3s_CAP_berd_003_u_l", "", 30, ""},
            {"d3s_CAP_berd_003_u_m", "", 30, ""},
            {"d3s_CAP_berd_003_u_n", "", 30, ""},
            {"d3s_CAP_berd_003_u_o", "", 30, ""},
            {"d3s_CAP_berd_003_u_p", "", 30, ""},
            {"d3s_CAP_berd_003_u_q", "", 30, ""},
            {"d3s_CAP_berd_003_u_r", "", 30, ""},
            {"d3s_CAP_berd_003_u_s", "", 30, ""},
            {"d3s_CAP_berd_003_u_t", "", 30, ""},
            {"d3s_CAP_berd_003_u_u", "", 30, ""},
            {"d3s_CAP_berd_003_u_v", "", 30, ""},
            {"d3s_CAP_berd_003_u_w", "", 30, ""},
            {"d3s_CAP_berd_003_u_x", "", 30, ""},
            {"d3s_CAP_berd_003_u_y", "", 30, ""},
            {"d3s_CAP_berd_003_u_z", "", 30, ""},
            {"d3s_CAP_berd_004_u_a", "", 30, ""},
            {"d3s_CAP_berd_004_u_b", "", 30, ""},
            {"d3s_CAP_berd_004_u_c", "", 30, ""},
            {"d3s_CAP_berd_004_u_d", "", 30, ""},
            {"d3s_CAP_berd_004_u_e", "", 30, ""},
            {"d3s_CAP_berd_004_u_f", "", 30, ""},
            {"d3s_CAP_berd_004_u_g", "", 30, ""},
            {"d3s_CAP_berd_004_u_i", "", 30, ""},
            {"d3s_CAP_berd_004_u_k", "", 30, ""},
            {"d3s_CAP_berd_004_u_n", "", 30, ""},
            {"d3s_CAP_berd_004_u_s", "", 30, ""},
            {"d3s_CAP_berd_004_u_j", "", 30, ""},
            {"d3s_CAP_berd_006_u_a", "", 30, ""},
            {"d3s_CAP_berd_006_u_b", "", 30, ""},
            {"d3s_CAP_berd_006_u_c", "", 30, ""},
            {"d3s_CAP_berd_006_u_d", "", 30, ""},
            {"d3s_CAP_berd_006_u_e", "", 30, ""},
            {"d3s_CAP_berd_006_u_f", "", 30, ""},
            {"d3s_CAP_berd_006_u_g", "", 30, ""},
            {"d3s_CAP_berd_006_u_h", "", 30, ""},
            {"d3s_CAP_berd_006_u_i", "", 30, ""},
            {"d3s_CAP_berd_006_u_j", "", 30, ""},
            {"d3s_CAP_berd_006_u_k", "", 30, ""},
            {"d3s_CAP_berd_006_u_l", "", 30, ""},
            {"d3s_CAP_berd_006_u_m", "", 30, ""},
            {"d3s_CAP_berd_006_u_n", "", 30, ""},
            {"d3s_CAP_berd_011_u_a", "", 30, ""},
            {"d3s_CAP_berd_011_u_b", "", 30, ""},
            {"d3s_CAP_berd_011_u_c", "", 30, ""},
            {"d3s_CAP_berd_011_u_d", "", 30, ""},
            {"d3s_CAP_berd_011_u_e", "", 30, ""},
            {"d3s_CAP_berd_011_u_f", "", 30, ""},
            {"d3s_CAP_berd_011_u_g", "", 30, ""},
            {"d3s_CAP_berd_011_u_h", "", 30, ""},
            {"d3s_CAP_berd_011_u_i", "", 30, ""},
            {"d3s_CAP_berd_011_u_j", "", 30, ""},
            {"d3s_CAP_berd_011_u_k", "", 30, ""},
            {"d3s_CAP_berd_011_u_l", "", 30, ""},
            {"d3s_CAP_berd_011_u_m", "", 30, ""},
            {"d3s_CAP_berd_011_u_n", "", 30, ""},
            {"d3s_CAP_berd_011_u_o", "", 30, ""},
            {"d3s_CAP_berd_011_u_p", "", 30, ""},
            {"d3s_CAP_berd_011_u_q", "", 30, ""},
            {"d3s_CAP_berd_011_u_r", "", 30, ""},
            {"d3s_CAP_berd_011_u_s", "", 30, ""},
            {"d3s_CAP_berd_011_u_t", "", 30, ""},
            {"d3s_CAP_berd_011_u_u", "", 30, ""},
            {"d3s_CAP_berd_011_u_v", "", 30, ""},
            {"d3s_CAP_berd_011_u_w", "", 30, ""},
            {"d3s_CAP_berd_011_u_x", "", 30, ""},
            {"d3s_CAP_char_sniper", "", 30, ""},
            {"d3s_CAP_beanie", "", 30, ""},
            {"d3s_CAP_beanie1", "", 30, ""},
            {"d3s_CAP_beanie2", "", 30, ""},
            {"d3s_CAP_beanie3", "", 30, ""},
            {"d3s_CAP_beanie4", "", 30, ""},
            {"d3s_CAP_beanie5", "", 30, ""},
            {"d3s_CAP_beanie6", "", 30, ""},
            {"d3s_CAP_beanie7", "", 30, ""},
            {"d3s_CAP_beanie8", "", 30, ""},
            {"d3s_CAP_beanie_1", "", 30, ""},
            {"d3s_CAP_beanie_1_a", "", 30, ""},
            {"d3s_CAP_beanie_1_b", "", 30, ""},
            {"d3s_CAP_beanie_1_c", "", 30, ""},
            {"d3s_CAP_beanie_1_d", "", 30, ""},
            {"d3s_CAP_beanie_1_e", "", 30, ""},
            {"d3s_CAP_beanie_1_f", "", 30, ""},
            {"d3s_CAP_beanie_1_g", "", 30, ""},
            {"d3s_CAP_beanie_1_h", "", 30, ""},
            {"d3s_CAP_beanie_1_i", "", 30, ""},
            {"d3s_CAP_beanie_1_j", "", 30, ""},
            {"d3s_CAP_beanie_1_k", "", 30, ""},
            {"d3s_CAP_beanie_1_l", "", 30, ""},
            {"d3s_CAP_beanie_1_m", "", 30, ""},
            {"d3s_CAP_beanie_2_a", "", 30, ""},
            {"d3s_CAP_beanie_2_b", "", 30, ""},
            {"d3s_CAP_beanie_2_c", "", 30, ""},
            {"d3s_CAP_beanie_2_d", "", 30, ""},
            {"d3s_CAP_beanie_2_e", "", 30, ""},
            {"d3s_CAP_beanie_2_f", "", 30, ""},
            {"d3s_CAP_beanie_2_g", "", 30, ""},
            {"d3s_CAP_beanie_2_h", "", 30, ""},
            {"d3s_CAP_beanie_2_i", "", 30, ""},
            {"d3s_CAP_beanie_2_j", "", 30, ""},
            {"d3s_CAP_beanie_2_k", "", 30, ""},
            {"d3s_CAP_beanie_2_l", "", 30, ""},
            {"d3s_CAP_beanie_2_m", "", 30, ""},
            {"d3s_CAP_beanie_2_n", "", 30, ""},
            {"d3s_CAP_beanie_2_o", "", 30, ""},
            {"d3s_CAP_Embacy", "", 30, ""},
            {"d3s_CAP_furcap", "", 30, ""},
            {"d3s_CAP_russelite_hat", "", 30, ""},
            {"d3s_CAP_Headgear", "", 30, ""},
            {"d3s_CAP_Headgear1", "", 30, ""},
            {"d3s_CAP_Headgear_1", "", 30, ""},
            {"d3s_CAP_Headgear1_1", "", 30, ""}
        };

        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Shades_Black", "", 20, "" },
            { "G_Shades_Blue", "", 20, "" },
            { "G_Shades_Green", "", 20, "" },
            { "G_Shades_Red", "", 20, "" },
            { "G_Sport_Blackred", "", 25, "" },
            { "G_Sport_BlackWhite", "", 25, "" },
            { "G_Sport_Blackyellow", "", 25, "" },
            { "G_Sport_Checkered", "", 25, "" },
            { "G_Sport_Greenblack", "", 25, "" },
            { "G_Sport_Red", "", 25, "" },
            { "G_Lowprofile", "", 20, "" },
            { "G_Squares", "", 20, "" },
            { "G_Aviator", "", 50, "" },
            { "G_Combat", "", 23, "" },
            { "G_Lady_Mirror", "", 26, "" },
            { "G_Lady_Dark", "", 26, "" },
            { "G_Lady_Blue", "", 26, "" },
            { "d3s_p_eyes_000_a", "", 50, "" },
            { "d3s_p_eyes_000_b", "", 50, "" },
            { "d3s_p_eyes_000_c", "", 50, "" },
            { "d3s_p_eyes_000_d", "", 50, "" },
            { "d3s_p_eyes_000_e", "", 50, "" },
            { "d3s_p_eyes_000_f", "", 50, "" },
            { "d3s_p_eyes_000_g", "", 50, "" },
            { "d3s_p_eyes_000_h", "", 50, "" },
            { "d3s_p_eyes_000_i", "", 50, "" },
            { "d3s_p_eyes_000_j", "", 50, "" },
            { "d3s_p_eyes_000_k", "", 50, "" },
            { "d3s_p_eyes_000_l", "", 50, "" },
            { "d3s_p_eyes_000_m", "", 50, "" },
            { "d3s_p_eyes_000_n", "", 50, "" },
            { "d3s_p_eyes_000_o", "", 50, "" },
            { "d3s_p_eyes_001", "", 50, "" },
            { "d3s_Glasses_scarf_a", "", 50, "" },
            { "d3s_Glasses_scarf_b", "", 50, "" },
            { "d3s_Glasses_scarf_c", "", 50, "" },
            { "d3s_Glasses_scarf1_a", "", 50, "" },
            { "d3s_Glasses_scarf1_b", "", 50, "" },
            { "d3s_Glasses_scarf1_c", "", 50, "" },
            { "d3s_Glasses_scarf1_d", "", 50, "" },
            { "d3s_Glasses_scarf2_a", "", 50, "" },
            { "d3s_Glasses_scarf2_b", "", 50, "" },
            { "d3s_Glasses_scarf2_c", "", 50, "" },
            { "d3s_Glasses_scarf2_d", "", 50, "" },
            { "d3s_Glasses_scarf2_e", "", 50, "" },
            { "d3s_Glasses_scarf2_f", "", 50, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_Safety_blue_F", "Saftey Blue", 50, "" },
            { "V_Safety_orange_F", "Saftey Orange", 50, "" },
            { "V_Safety_yellow_F", "Saftey Yellow", 50, "" },
            { "d3s_vest_1", "", 450, "" },
            { "d3s_vest_1_a", "", 450, "" },
            { "d3s_vest_1_b", "", 450, "" },
            { "d3s_vest_1_c", "", 450, "" },
            { "d3s_vest_1_d", "", 450, "" },
            { "d3s_vest_1_e", "", 450, "" },
            { "d3s_vest_1_f", "", 450, "" },
            { "d3s_vest_1_g", "", 450, "" },
            { "d3s_vest_1_h", "", 450, "" },
            { "d3s_vest_1_i", "", 450, "" },
            { "d3s_vest_1_j", "", 450, "" },
            { "d3s_vest_1_k", "", 450, "" },
            { "d3s_vest_1_l", "", 450, "" },
            { "d3s_vest_1_m", "", 450, "" },
            { "d3s_vest_1_n", "", 450, "" },
            { "d3s_vest_1_o", "", 450, "" },
            { "d3s_vest_1_p", "", 450, "" },
            { "d3s_vest_1_q", "", 450, "" },
            { "d3s_vest_1_r", "", 450, "" },
            { "d3s_vest_1_s", "", 450, "" },
            { "d3s_vest_1_t", "", 450, "" },
            { "d3s_vest_1_u", "", 450, "" },
            { "d3s_vest_1_v", "", 450, "" },
            { "d3s_vest_1_w", "", 450, "" },
            { "d3s_vest_1_x", "", 450, "" },
            { "d3s_vest_1_y", "", 450, "" },
            { "d3s_vest_1_z", "", 450, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "B_OutdoorPack_blk", "", 150, "" },
            { "B_AssaultPack_khk", "", 200, "" },
            { "B_AssaultPack_dgtl", "", 200, "" },
            { "B_AssaultPack_rgr", "", 200, "" },
            { "B_AssaultPack_sgg", "", 200, "" },
            { "B_AssaultPack_blk", "", 200, "" },
            { "B_AssaultPack_cbr", "", 200, "" },
            { "B_AssaultPack_mcamo", "", 200, "" },
            { "B_AssaultPack_tna_f", "", 200, "" },
            { "B_TacticalPack_oli", "", 200, "" },
            { "B_Kitbag_mcamo", "", 300, "" },
            { "B_Kitbag_sgg", "", 300, "" },
            { "B_Kitbag_cbr", "", 300, "" },
            { "B_FieldPack_blk", "", 400, "" },
            { "B_FieldPack_ocamo", "", 400, "" },
            { "B_FieldPack_oucamo", "", 400, "" },
            { "B_FieldPack_ghex_f", "", 400, "" },
            { "B_Bergen_sgg", "", 500, "" },
            { "B_Bergen_mcamo", "", 500, "" },
            { "B_Bergen_rgr", "", 500, "" },
            { "B_Bergen_blk", "", 500, "" },
            { "B_Carryall_ocamo", "", 550, "" },
            { "B_Carryall_oucamo", "", 550, "" },
            { "B_Carryall_mcamo", "", 550, "" },
            { "B_Carryall_oli", "", 550, "" },
            { "B_Carryall_khk", "", 550, "" },
            { "B_Carryall_cbr", "", 550, "" },
            { "B_Carryall_ghex_f", "", 650, "" },
            { "B_Bergen_dgtl_f", "", 650, "" },
            { "B_AssaultPack_mcamo", "", 200, "" },
            { "B_TacticalPack_oli", "", 30, "" },
            { "B_Kitbag_mcamo", "", 300, "" },
            { "B_Kitbag_sgg", "", 300, "" },
            { "B_Kitbag_cbr", "", 300, "" },
            { "B_FieldPack_blk", "", 500, "" },
            { "B_FieldPack_ocamo", "", 500, "" },
            { "B_FieldPack_oucamo", "", 500, "" },
            { "B_Bergen_sgg", "", 650, "" },
            { "B_Bergen_mcamo", "", 650, "" },
            { "B_Bergen_rgr", "", 650, "" },
            { "B_Bergen_blk", "", 650, "" },
            { "B_Carryall_ocamo", "", 750, "" },
            { "B_Carryall_oucamo", "", 750, "" },
            { "B_Carryall_mcamo", "", 750, "" },
            { "B_Carryall_oli", "", 750, "" },
            { "B_Carryall_khk", "", 750, "" },
            { "B_Carryall_cbr", "", 750, "" },
            { "casper_beautifulbackpack", "", 460, "" },
            { "casper_cockbackpack", "", 460, "" },
            { "casper_facbackpack", "", 460, "" },
            { "casper_hellokittybackpack", "", 460, "" },
            { "casper_mcdonaldsbackpack", "", 460, "" },
            { "casper_nemobackpack", "", 460, "" },
            { "casper_ppatrolbackpack", "", 460, "" },
            { "d3s_backpack", "", 800, "" },
            { "d3s_backpack_a", "", 800, "" },
            { "d3s_backpack_b", "", 800, "" },
            { "d3s_backpack_c", "", 800, "" },
            { "d3s_backpack_d", "", 800, "" },
            { "d3s_backpack_e", "", 800, "" },
            { "d3s_backpack_f", "", 800, "" },
            { "d3s_backpack_g", "", 800, "" },
            { "d3s_backpack_h", "", 800, "" },
            { "d3s_backpack_i", "", 800, "" },
            { "d3s_backpack_j", "", 800, "" },
            { "d3s_backpack_k", "", 800, "" },
            { "d3s_backpack_l", "", 800, "" },
            { "d3s_backpack_m", "", 800, "" }
        };
    };

    class rebel {
        title = "STR_Shops_C_Rebel";
        conditions = "";
        side = "";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "AL_BlackSheepUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 189" },
            { "AL_BrotherhoodUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 50" },
            { "AL_MillersUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 64" },
            { "AL_ManarelloUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 16" },
            { "AL_UrFatUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 51" },
            { "AL_NotoriousUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 118" },
            { "AL_CrownCartelUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 136" },
            { "AL_PullUpBoysUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 152" },
            { "AL_SyndicateUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 81" },
            { "AL_YakuzaUniform", "", 30, "group player getVariable ['gang_id',-1] isEqualTo 188" },
            { "TRYK_SUITS_BLK_F", "Capone Family Uniform", 30, "group player getVariable ['gang_id',-1] isEqualTo 100" },
            { "TRYK_U_B_BLKOCP_CombatUniform", "Outer Haven Uniform", 30, "group player getVariable ['gang_id',-1] isEqualTo 117" },
            { "U_B_survival_uniform", "", 200, ""},
            {"TRYK_U_B_PCUGHs","",200,""},
            {"TRYK_U_B_BLOD_T","Black T Green P",200,""},
            {"TRYK_U_B_BLKTANR_CombatUniformTshirt","Black T Tan P II",200,""},
            {"TRYK_U_B_BLTAN_T","Black T Dark Tan P",200,""},
            {"TRYK_U_B_fleece_UCP","Leader",200,""},
            {"TRYK_U_B_ODTANR_CombatUniformTshirt","Green T Tan P",200,""},
            {"TRYK_U_B_PCUGs_OD","Jeans Green Hood",200,""},
            {"TRYK_U_B_PCUGs_gry","Jeans Gray Hood ",200,""},
            {"TRYK_U_B_PCUGs_BLK","Jeans Black Hood",200,""},
            {"TRYK_U_B_C02_Tsirt","Baggy Jeans + Black T",200,""},
            {"TRYK_OVERALL_SAGE_BLKboots_nk","Coveralls Green",200,""},
            {"TRYK_OVERALL_nok_flesh","Coveralls Tan",200,""},
            {"TRYK_U_B_wh_blk_Rollup_CombatUniform","White T Black Cargos",200,""},
            {"TRYK_U_B_wh_tan_Rollup_CombatUniform","White T Tan Cargos",200,""},
            {"TRYK_U_pad_hood_Blk","Black Hood Tan Cargos",200,""},
            {"TRYK_U_denim_hood_blk","Black Hood Jeans II",200,""},
            {"TRYK_U_denim_jersey_blk","Black T & Jeans",200,""},
            {"TRYK_U_denim_jersey_blu","Blue T & Jeans",200,""},
            {"TRYK_U_denim_hood_nc","Green Hood & Jeans",200,""},
            {"TRYK_U_taki_wh","Tan Mid East",200,""},
            {"TRYK_U_taki_BLK","Black Mid East",200,""},
            {"TRYK_U_taki_COY","Brown Mid East ",200,""},
            {"TRYK_U_B_BLK_T_BK","Black Jeans (Black)",200,""},
            {"TRYK_U_B_BLK_T_WH","Black Jeans (White)",200,""},
            {"TRYK_U_B_Denim_T_BK","Grey Jeans (Black)",200,""},
            {"TRYK_U_B_Denim_T_WH","Grey Jeans (White)",200,""},
            { "TRYK_U_B_ARO1_CBR_R_CombatUniform", "", 200, "" },
            { "TRYK_U_B_ARO1_GR_CombatUniform", "", 200, "" },
            { "TRYK_U_B_ARO1_GRY_CombatUniform", "", 200, "" },
            { "TRYK_DMARPAT_T", "", 200, "" },
            { "TRYK_U_B_AOR2_BLK_R_CombatUniform", "", 200, "" },
            { "TRYK_U_B_AOR2_OD_CombatUniform", "", 200, "" },
            { "TRYK_U_B_BLKOCP_CombatUniform", "", 200, "" },
            { "TRYK_U_B_BLKTAN_CombatUniform", "", 200, "" },
            { "TRYK_U_B_C01_Tsirt", "", 200, "" },
            { "TRYK_U_B_BLK3CD_Tshirt", "", 200, "" },
            { "TRYK_U_B_BLKTAN", "", 200, "" },
            { "TRYK_U_B_BLK_OD", "", 200, "" },
            { "TRYK_U_B_OD_BLK", "", 200, "" },
            { "TRYK_U_B_ODTAN", "", 200, "" },
            { "TRYK_U_B_BLK_TAN_2", "", 200, "" },
            { "TRYK_U_B_3CD_BLK_BDUTshirt2", "", 200, "" },
            { "TRYK_U_B_GRYOCP_CombatUniform", "", 200, "" },
            { "TRYK_U_Bts_UCP_PCUs", "", 200, "" },
            { "TRYK_U_Bts_GRYGRY_PCUs", "", 200, "" },
            { "TRYK_U_B_PCUHs", "", 200, "" },
            { "TRYK_U_B_PCUODHs", "", 200, "" },
            { "TRYK_U_B_PCUs_R", "", 200, "" },
            { "TRYK_U_B_BLK_tan_Rollup_CombatUniform", "", 200, "" },
            { "TRYK_U_B_wh_OD_Rollup_CombatUniform", "", 200, "" },
            { "TRYK_shirts_DENIM_ylb", "", 200, "" },
            { "TRYK_shirts_DENIM_BK_Sleeve", "", 200, "" },
            { "TRYK_shirts_DENIM_BWH_Sleeve", "", 200, "" },
            { "TRYK_shirts_DENIM_R_Sleeve", "", 200, "" },
            { "TRYK_shirts_DENIM_RED2_Sleeve", "", 200, "" },
            { "TRYK_shirts_TAN_PAD_BK", "", 200, "" },
            { "TRYK_shirts_BLK_PAD_BL", "", 200, "" },
            { "TRYK_shirts_PAD_BLW", "", 200, "" },
            { "TRYK_shirts_PAD", "", 200, "" },
            { "TRYK_hoodie_FR", "", 200, "" },
            { "TRYK_U_hood_mc", "", 200, "" },
            { "TRYK_U_pad_j_blk", "", 200, "" },
            { "TRYK_U_taki_BL", "", 200, "" },
            { "TRYK_ZARATAKI", "", 200, "" },
            { "TRYK_ZARATAKI2", "", 200, "" },
            { "TRYK_ZARATAKI3", "", 200, "" },

            { "travis_polocookiemonster", "", 30, "" },
            { "travis_poloapple", "", 30, "" },
            { "travis_polohellokitty", "", 30, "" },
            { "travis_polohellokitty1", "", 30, "" },
            { "travis_timmac", "", 30, "" },
            { "travis_Butts", "", 30, "" },
            { "travis_poloaustralia", "", 30, "" },
            { "travis_polospongebob", "", 30, "" },
            { "travis_polopatrickstar", "", 30, "" },
            { "travis_polocanda", "", 30, "" },
            { "travis_pololove", "", 30, "" },
            { "travis_polofuck", "", 30, "" },
            { "travis_polococacola", "", 30, "" },
            { "travis_poloangelo", "", 30, "" },
            { "travis_polomrbong", "", 30, "" },
            { "travis_polomoon", "", 30, "" },
            { "travis_polodino", "", 30, "" },
            { "travis_polostunt", "", 30, "" },
            { "travis_poloface", "", 30, "" },
            { "travis_avengers", "", 30, "" },
            { "travis_doge", "", 30, "" },
            { "travis_fuckit", "", 30, "" },
            { "travis_illuminati", "", 30, "" },
            { "travis_jeff", "", 30, "" },
            { "travis_kappa", "", 30, "" },
            { "travis_married", "", 30, "" },
            { "travis_marvel", "", 30, "" },
            { "travis_mexicantroll", "", 30, "" },
            { "travis_minion", "", 30, "" },
            { "travis_monstercat", "", 30, "" },
            { "travis_nike", "", 30, "" },
            { "travis_pancake", "", 30, "" },
            { "travis_shield", "", 30, "" },
            { "travis_smile", "", 30, "" },
            { "travis_Batman", "", 30, "" },
            { "travis_tux", "", 30, "" },
            { "travis_twitch", "", 30, "" },
            { "travis_yaoming", "", 30, "" },
            { "travis_smokeweed", "", 30, "" },
            { "travis_Snoopy", "", 30, "" },
            { "travis_Coco", "", 30, "" },
            { "travis_Ciggy", "", 30, "" },
            { "travis_Adidas", "", 30, "" },
            { "kojixus_wolf", "", 30, "" },
            { "kojixus_picklerick", "", 30, "" },
            { "kojixus_russianpepe", "", 30, "" },
            { "kojixus_angrypepe", "", 30, "" },
            { "kojixus_trippieredd", "", 30, "" },
            { "kojixus_mexicanfarmer", "", 30, "" },
            { "kojixus_xxxtenaction", "", 30, "" },
            { "travis_polopsisyndicate", "", 30, "" },
            { "kojixus_psiblack", "", 30, "" },
            { "kojixus_psi", "", 30, "" },
            { "kojixus_wizard", "", 30, "" },
            { "kojixus_vapenation", "", 30, "" },
            { "kojixus_supreme", "", 30, "" },
            { "kojixus_treyway", "", 30, "" },
            {"d3s_uniform_jbib_008_a", "", 30, ""},
            {"d3s_uniform_jbib_008_aa", "", 30, ""},
            {"d3s_uniform_jbib_008_ab", "", 30, ""},
            {"d3s_uniform_jbib_008_ac", "", 30, ""},
            {"d3s_uniform_jbib_008_ad", "", 30, ""},
            {"d3s_uniform_jbib_008_ae", "", 30, ""},
            {"d3s_uniform_jbib_008_af", "", 30, ""},
            {"d3s_uniform_jbib_008_b", "", 30, ""},
            {"d3s_uniform_jbib_008_ba", "", 30, ""},
            {"d3s_uniform_jbib_008_bb", "", 30, ""},
            {"d3s_uniform_jbib_008_bc", "", 30, ""},
            {"d3s_uniform_jbib_008_bd", "", 30, ""},
            {"d3s_uniform_jbib_008_be", "", 30, ""},
            {"d3s_uniform_jbib_008_bf", "", 30, ""},
            {"d3s_uniform_jbib_008_c", "", 30, ""},
            {"d3s_uniform_jbib_008_ca", "", 30, ""},
            {"d3s_uniform_jbib_008_cb", "", 30, ""},
            {"d3s_uniform_jbib_008_cc", "", 30, ""},
            {"d3s_uniform_jbib_008_cd", "", 30, ""},
            {"d3s_uniform_jbib_008_ce", "", 30, ""},
            {"d3s_uniform_jbib_008_cf", "", 30, ""},
            {"d3s_uniform_jbib_008_d", "", 30, ""},
            {"d3s_uniform_jbib_008_da", "", 30, ""},
            {"d3s_uniform_jbib_008_db", "", 30, ""},
            {"d3s_uniform_jbib_008_dc", "", 30, ""},
            {"d3s_uniform_jbib_008_dd", "", 30, ""},
            {"d3s_uniform_jbib_008_de", "", 30, ""},
            {"d3s_uniform_jbib_008_df", "", 30, ""},
            {"d3s_uniform_jbib_008_e", "", 30, ""},
            {"d3s_uniform_jbib_008_ea", "", 30, ""},
            {"d3s_uniform_jbib_008_eb", "", 30, ""},
            {"d3s_uniform_jbib_008_ec", "", 30, ""},
            {"d3s_uniform_jbib_008_ed", "", 30, ""},
            {"d3s_uniform_jbib_008_ee", "", 30, ""},
            {"d3s_uniform_jbib_008_ef", "", 30, ""},
            {"d3s_uniform_jbib_008_f", "", 30, ""},
            {"d3s_uniform_jbib_008_fa", "", 30, ""},
            {"d3s_uniform_jbib_008_fb", "", 30, ""},
            {"d3s_uniform_jbib_008_fc", "", 30, ""},
            {"d3s_uniform_jbib_008_fd", "", 30, ""},
            {"d3s_uniform_jbib_008_fe", "", 30, ""},
            {"d3s_uniform_jbib_008_ff", "", 30, ""},
            {"d3s_uniform_jbib_008_g", "", 30, ""},
            {"d3s_uniform_jbib_008_ga", "", 30, ""},
            {"d3s_uniform_jbib_008_gb", "", 30, ""},
            {"d3s_uniform_jbib_008_gc", "", 30, ""},
            {"d3s_uniform_jbib_008_gd", "", 30, ""},
            {"d3s_uniform_jbib_008_ge", "", 30, ""},
            {"d3s_uniform_jbib_008_gf", "", 30, ""},
            {"d3s_uniform_jbib_008_h", "", 30, ""},
            {"d3s_uniform_jbib_008_ha", "", 30, ""},
            {"d3s_uniform_jbib_008_hb", "", 30, ""},
            {"d3s_uniform_jbib_008_hc", "", 30, ""},
            {"d3s_uniform_jbib_008_hd", "", 30, ""},
            {"d3s_uniform_jbib_008_he", "", 30, ""},
            {"d3s_uniform_jbib_008_hf", "", 30, ""},
            {"d3s_uniform_jbib_008_i", "", 30, ""},
            {"d3s_uniform_jbib_008_ia", "", 30, ""},
            {"d3s_uniform_jbib_008_ib", "", 30, ""},
            {"d3s_uniform_jbib_008_ic", "", 30, ""},
            {"d3s_uniform_jbib_008_id", "", 30, ""},
            {"d3s_uniform_jbib_008_ie", "", 30, ""},
            {"d3s_uniform_jbib_008_if", "", 30, ""},
            {"d3s_uniform_jbib_008_j", "", 30, ""},
            {"d3s_uniform_jbib_008_ja", "", 30, ""},
            {"d3s_uniform_jbib_008_jb", "", 30, ""},
            {"d3s_uniform_jbib_008_jc", "", 30, ""},
            {"d3s_uniform_jbib_008_jd", "", 30, ""},
            {"d3s_uniform_jbib_008_je", "", 30, ""},
            {"d3s_uniform_jbib_008_jf", "", 30, ""},
            {"d3s_uniform_jbib_008_k", "", 30, ""},
            {"d3s_uniform_jbib_008_ka", "", 30, ""},
            {"d3s_uniform_jbib_008_kb", "", 30, ""},
            {"d3s_uniform_jbib_008_kc", "", 30, ""},
            {"d3s_uniform_jbib_008_kd", "", 30, ""},
            {"d3s_uniform_jbib_008_ke", "", 30, ""},
            {"d3s_uniform_jbib_008_kf", "", 30, ""},
            {"d3s_uniform_jbib_008_l", "", 30, ""},
            {"d3s_uniform_jbib_008_la", "", 30, ""},
            {"d3s_uniform_jbib_008_lb", "", 30, ""},
            {"d3s_uniform_jbib_008_lc", "", 30, ""},
            {"d3s_uniform_jbib_008_ld", "", 30, ""},
            {"d3s_uniform_jbib_008_le", "", 30, ""},
            {"d3s_uniform_jbib_008_lf", "", 30, ""},
            {"d3s_uniform_jbib_008_m", "", 30, ""},
            {"d3s_uniform_jbib_008_ma", "", 30, ""},
            {"d3s_uniform_jbib_008_mb", "", 30, ""},
            {"d3s_uniform_jbib_008_mc", "", 30, ""},
            {"d3s_uniform_jbib_008_md", "", 30, ""},
            {"d3s_uniform_jbib_008_me", "", 30, ""},
            {"d3s_uniform_jbib_008_mf", "", 30, ""},
            {"d3s_uniform_jbib_008_n", "", 30, ""},
            {"d3s_uniform_jbib_008_na", "", 30, ""},
            {"d3s_uniform_jbib_008_nb", "", 30, ""},
            {"d3s_uniform_jbib_008_nc", "", 30, ""},
            {"d3s_uniform_jbib_008_nd", "", 30, ""},
            {"d3s_uniform_jbib_008_ne", "", 30, ""},
            {"d3s_uniform_jbib_008_nf", "", 30, ""},
            {"d3s_uniform_jbib_008_o", "", 30, ""},
            {"d3s_uniform_jbib_008_oa", "", 30, ""},
            {"d3s_uniform_jbib_008_ob", "", 30, ""},
            {"d3s_uniform_jbib_008_oc", "", 30, ""},
            {"d3s_uniform_jbib_008_od", "", 30, ""},
            {"d3s_uniform_jbib_008_oe", "", 30, ""},
            {"d3s_uniform_jbib_008_of", "", 30, ""}
        };

        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            {"d3s_CAP_christmas_head_a", "", 30, ""},
            {"d3s_CAP_christmas_head_b", "", 30, ""},
            {"d3s_CAP_christmas_head_c", "", 30, ""},
            {"d3s_CAP_christmas_head_d", "", 30, ""},
            {"d3s_CAP_christmas_head_e", "", 30, ""},
            {"d3s_CAP_christmas_head_f", "", 30, ""},
            {"d3s_CAP_christmas_head_g", "", 30, ""},
            {"d3s_CAP_christmas_head_h", "", 30, ""},
            {"d3s_CAP_christmas_head1", "", 30, ""},
            { "H_Cap_Oli", "", 30, "" },
            {"d3s_CAP_christmas_head2_a", "", 30, ""},
            {"d3s_CAP_christmas_head2_b", "", 30, ""},
            {"d3s_CAP_christmas_head2_c", "", 30, ""},
            {"d3s_CAP_christmas_head2_d", "", 30, ""},
            {"d3s_CAP_christmas_head3_a", "", 30, ""},
            {"d3s_CAP_christmas_head3_b", "", 30, ""},
            {"d3s_CAP_christmas_head3_c", "", 30, ""},
            {"d3s_CAP_christmas_head3_d", "", 30, ""},
            {"d3s_CAP_christmas_head4_a", "", 30, ""},
            {"d3s_CAP_christmas_head4_b", "", 30, ""},
            {"d3s_CAP_christmas_head4_c", "", 30, ""},
            {"d3s_CAP_christmas_head4_d", "", 30, ""},
            {"d3s_CAP_christmas_head4_e", "", 30, ""},
            {"d3s_CAP_christmas_head4_f", "", 30, ""},
            {"d3s_CAP_christmas_head4_g", "", 30, ""},
            {"d3s_CAP_christmas_head4_h", "", 30, ""},
            {"d3s_CAP_christmas_head5_a", "", 30, ""},
            {"d3s_CAP_christmas_head5_b", "", 30, ""},
            {"d3s_CAP_christmas_head5_c", "", 30, ""},
            {"d3s_CAP_christmas_head5_d", "", 30, ""},
            {"d3s_CAP_christmas_head5_e", "", 30, ""},
            {"d3s_CAP_christmas_head5_f", "", 30, ""},
            {"d3s_CAP_christmas_head5_g", "", 30, ""},
            {"d3s_CAP_christmas_head5_h", "", 30, ""},
            {"d3s_CAP_p_head_000_a", "", 30, ""},
            {"d3s_CAP_p_head_000_b", "", 30, ""},
            {"d3s_CAP_p_head_000_c", "", 30, ""},
            {"d3s_CAP_p_head_000_d", "", 30, ""},
            {"d3s_CAP_p_head_000_e", "", 30, ""},
            {"d3s_CAP_p_head_000_f", "", 30, ""},
            {"d3s_CAP_p_head_000_g", "", 30, ""},
            {"d3s_CAP_p_head_000_h", "", 30, ""},
            {"d3s_CAP_p_head_000_i", "", 30, ""},
            {"d3s_CAP_p_head_000_j", "", 30, ""},
            {"d3s_CAP_p_head_000_k", "", 30, ""},
            {"d3s_CAP_p_head_000_l", "", 30, ""},
            {"d3s_CAP_p_head_000_m", "", 30, ""},
            {"d3s_CAP_p_head_000_n", "", 30, ""},
            {"d3s_CAP_p_head_000_o", "", 30, ""},
            {"d3s_CAP_p_head_000_p", "", 30, ""},
            {"d3s_CAP_p_head_000_q", "", 30, ""},
            {"d3s_CAP_p_head_000_r", "", 30, ""},
            {"d3s_CAP_p_head_000_s", "", 30, ""},
            {"d3s_CAP_p_head_000_t", "", 30, ""},
            {"d3s_CAP_p_head_001_a", "", 30, ""},
            {"d3s_CAP_p_head_001_b", "", 30, ""},
            {"d3s_CAP_p_head_001_c", "", 30, ""},
            {"d3s_CAP_p_head_001_d", "", 30, ""},
            {"d3s_CAP_p_head_001_e", "", 30, ""},
            {"d3s_CAP_p_head_001_f", "", 30, ""},
            {"d3s_CAP_p_head_001_g", "", 30, ""},
            {"d3s_CAP_p_head_001_h", "", 30, ""},
            {"d3s_CAP_p_head_001_i", "", 30, ""},
            {"d3s_CAP_p_head_001_j", "", 30, ""},
            {"d3s_CAP_p_head_004_a", "", 30, ""},
            {"d3s_CAP_p_head_004_b", "", 30, ""},
            {"d3s_CAP_p_head_004_c", "", 30, ""},
            {"d3s_CAP_p_head_004_d", "", 30, ""},
            {"d3s_CAP_p_head_004_e", "", 30, ""},
            {"d3s_CAP_p_head_004_f", "", 30, ""},
            {"d3s_CAP_p_head_004_g", "", 30, ""},
            {"d3s_CAP_p_head_004_h", "", 30, ""},
            {"d3s_CAP_p_head_004_i", "", 30, ""},
            {"d3s_CAP_p_head_004_j", "", 30, ""},
            {"d3s_CAP_p_head_004_k", "", 30, ""},
            {"d3s_CAP_p_head_004_l", "", 30, ""},
            {"d3s_CAP_p_head_004_m", "", 30, ""},
            {"d3s_CAP_p_head_005_a", "", 30, ""},
            {"d3s_CAP_p_head_005_b", "", 30, ""},
            {"d3s_CAP_p_head_005_c", "", 30, ""},
            {"d3s_CAP_p_head_005_d", "", 30, ""},
            {"d3s_CAP_p_head_005_e", "", 30, ""},
            {"d3s_CAP_p_head_005_f", "", 30, ""},
            {"d3s_CAP_p_head_005_g", "", 30, ""},
            {"d3s_CAP_p_head_005_h", "", 30, ""},
            {"d3s_CAP_p_head_005_i", "", 30, ""},
            {"d3s_CAP_p_head_005_j", "", 30, ""},
            {"d3s_CAP_p_head_005_k", "", 30, ""},
            {"d3s_CAP_p_head_005_l", "", 30, ""},
            {"d3s_CAP_p_head_005_m", "", 30, ""},
            {"d3s_CAP_p_head_005_n", "", 30, ""},
            {"d3s_CAP_p_head_005_o", "", 30, ""},
            {"d3s_CAP_p_head_005_p", "", 30, ""},
            {"d3s_CAP_p_head_005_q", "", 30, ""},
            {"d3s_CAP_p_head_005_r", "", 30, ""},
            {"d3s_CAP_p_head_005_s", "", 30, ""},
            {"d3s_CAP_p_head_005_t", "", 30, ""},
            {"d3s_CAP_p_head_005_u", "", 30, ""},
            {"d3s_CAP_p_head_005_v", "", 30, ""},
            {"d3s_CAP_p_head_005_w", "", 30, ""},
            {"d3s_CAP_p_head_005_x", "", 30, ""},
            {"d3s_CAP_p_head_005_y", "", 30, ""},
            {"d3s_CAP_p_head_005_z", "", 30, ""},
            {"d3s_CAP_p_head_006_a", "", 30, ""},
            {"d3s_CAP_p_head_006_b", "", 30, ""},
            {"d3s_CAP_berd_000_u_a", "", 30, ""},
            {"d3s_CAP_berd_000_u_b", "", 30, ""},
            {"d3s_CAP_berd_000_u_c", "", 30, ""},
            {"d3s_CAP_berd_000_u_d", "", 30, ""},
            {"d3s_CAP_berd_000_u_e", "", 30, ""},
            {"d3s_CAP_berd_002_u_a", "", 30, ""},
            {"d3s_CAP_berd_002_u_b", "", 30, ""},
            {"d3s_CAP_berd_002_u_c", "", 30, ""},
            {"d3s_CAP_berd_002_u_d", "", 30, ""},
            {"d3s_CAP_berd_002_u_e", "", 30, ""},
            {"d3s_CAP_berd_002_u_f", "", 30, ""},
            {"d3s_CAP_berd_002_u_g", "", 30, ""},
            {"d3s_CAP_berd_002_u_h", "", 30, ""},
            {"d3s_CAP_berd_002_u_i", "", 30, ""},
            {"d3s_CAP_berd_002_u_j", "", 30, ""},
            {"d3s_CAP_berd_002_u_k", "", 30, ""},
            {"d3s_CAP_berd_002_u_l", "", 30, ""},
            {"d3s_CAP_berd_002_u_m", "", 30, ""},
            {"d3s_CAP_berd_002_u_n", "", 30, ""},
            {"d3s_CAP_berd_002_u_o", "", 30, ""},
            {"d3s_CAP_berd_002_u_p", "", 30, ""},
            {"d3s_CAP_berd_002_u_q", "", 30, ""},
            {"d3s_CAP_berd_002_u_r", "", 30, ""},
            {"d3s_CAP_berd_002_u_s", "", 30, ""},
            {"d3s_CAP_berd_002_u_t", "", 30, ""},
            {"d3s_CAP_berd_002_u_u", "", 30, ""},
            {"d3s_CAP_berd_002_u_v", "", 30, ""},
            {"d3s_CAP_berd_002_u_w", "", 30, ""},
            {"d3s_CAP_berd_002_u_x", "", 30, ""},
            {"d3s_CAP_berd_002_u_y", "", 30, ""},
            {"d3s_CAP_berd_002_u_z", "", 30, ""},
            {"d3s_CAP_berd_003_u_a", "", 30, ""},
            {"d3s_CAP_berd_003_u_b", "", 30, ""},
            {"d3s_CAP_berd_003_u_c", "", 30, ""},
            {"d3s_CAP_berd_003_u_d", "", 30, ""},
            {"d3s_CAP_berd_003_u_e", "", 30, ""},
            {"d3s_CAP_berd_003_u_f", "", 30, ""},
            {"d3s_CAP_berd_003_u_g", "", 30, ""},
            {"d3s_CAP_berd_003_u_h", "", 30, ""},
            {"d3s_CAP_berd_003_u_i", "", 30, ""},
            {"d3s_CAP_berd_003_u_j", "", 30, ""},
            {"d3s_CAP_berd_003_u_k", "", 30, ""},
            {"d3s_CAP_berd_003_u_l", "", 30, ""},
            {"d3s_CAP_berd_003_u_m", "", 30, ""},
            {"d3s_CAP_berd_003_u_n", "", 30, ""},
            {"d3s_CAP_berd_003_u_o", "", 30, ""},
            {"d3s_CAP_berd_003_u_p", "", 30, ""},
            {"d3s_CAP_berd_003_u_q", "", 30, ""},
            {"d3s_CAP_berd_003_u_r", "", 30, ""},
            {"d3s_CAP_berd_003_u_s", "", 30, ""},
            {"d3s_CAP_berd_003_u_t", "", 30, ""},
            {"d3s_CAP_berd_003_u_u", "", 30, ""},
            {"d3s_CAP_berd_003_u_v", "", 30, ""},
            {"d3s_CAP_berd_003_u_w", "", 30, ""},
            {"d3s_CAP_berd_003_u_x", "", 30, ""},
            {"d3s_CAP_berd_003_u_y", "", 30, ""},
            {"d3s_CAP_berd_003_u_z", "", 30, ""},
            {"d3s_CAP_berd_004_u_a", "", 30, ""},
            {"d3s_CAP_berd_004_u_b", "", 30, ""},
            {"d3s_CAP_berd_004_u_c", "", 30, ""},
            {"d3s_CAP_berd_004_u_d", "", 30, ""},
            {"d3s_CAP_berd_004_u_e", "", 30, ""},
            {"d3s_CAP_berd_004_u_f", "", 30, ""},
            {"d3s_CAP_berd_004_u_g", "", 30, ""},
            {"d3s_CAP_berd_004_u_i", "", 30, ""},
            {"d3s_CAP_berd_004_u_k", "", 30, ""},
            {"d3s_CAP_berd_004_u_n", "", 30, ""},
            {"d3s_CAP_berd_004_u_s", "", 30, ""},
            {"d3s_CAP_berd_004_u_j", "", 30, ""},
            {"d3s_CAP_berd_006_u_a", "", 30, ""},
            {"d3s_CAP_berd_006_u_b", "", 30, ""},
            {"d3s_CAP_berd_006_u_c", "", 30, ""},
            {"d3s_CAP_berd_006_u_d", "", 30, ""},
            {"d3s_CAP_berd_006_u_e", "", 30, ""},
            {"d3s_CAP_berd_006_u_f", "", 30, ""},
            {"d3s_CAP_berd_006_u_g", "", 30, ""},
            {"d3s_CAP_berd_006_u_h", "", 30, ""},
            {"d3s_CAP_berd_006_u_i", "", 30, ""},
            {"d3s_CAP_berd_006_u_j", "", 30, ""},
            {"d3s_CAP_berd_006_u_k", "", 30, ""},
            {"d3s_CAP_berd_006_u_l", "", 30, ""},
            {"d3s_CAP_berd_006_u_m", "", 30, ""},
            {"d3s_CAP_berd_006_u_n", "", 30, ""},
            {"d3s_CAP_berd_011_u_a", "", 30, ""},
            {"d3s_CAP_berd_011_u_b", "", 30, ""},
            {"d3s_CAP_berd_011_u_c", "", 30, ""},
            {"d3s_CAP_berd_011_u_d", "", 30, ""},
            {"d3s_CAP_berd_011_u_e", "", 30, ""},
            {"d3s_CAP_berd_011_u_f", "", 30, ""},
            {"d3s_CAP_berd_011_u_g", "", 30, ""},
            {"d3s_CAP_berd_011_u_h", "", 30, ""},
            {"d3s_CAP_berd_011_u_i", "", 30, ""},
            {"d3s_CAP_berd_011_u_j", "", 30, ""},
            {"d3s_CAP_berd_011_u_k", "", 30, ""},
            {"d3s_CAP_berd_011_u_l", "", 30, ""},
            {"d3s_CAP_berd_011_u_m", "", 30, ""},
            {"d3s_CAP_berd_011_u_n", "", 30, ""},
            {"d3s_CAP_berd_011_u_o", "", 30, ""},
            {"d3s_CAP_berd_011_u_p", "", 30, ""},
            {"d3s_CAP_berd_011_u_q", "", 30, ""},
            {"d3s_CAP_berd_011_u_r", "", 30, ""},
            {"d3s_CAP_berd_011_u_s", "", 30, ""},
            {"d3s_CAP_berd_011_u_t", "", 30, ""},
            {"d3s_CAP_berd_011_u_u", "", 30, ""},
            {"d3s_CAP_berd_011_u_v", "", 30, ""},
            {"d3s_CAP_berd_011_u_w", "", 30, ""},
            {"d3s_CAP_berd_011_u_x", "", 30, ""},
            {"d3s_CAP_char_sniper", "", 30, ""},
            {"d3s_CAP_beanie", "", 30, ""},
            {"d3s_CAP_beanie1", "", 30, ""},
            {"d3s_CAP_beanie2", "", 30, ""},
            {"d3s_CAP_beanie3", "", 30, ""},
            {"d3s_CAP_beanie4", "", 30, ""},
            {"d3s_CAP_beanie5", "", 30, ""},
            {"d3s_CAP_beanie6", "", 30, ""},
            {"d3s_CAP_beanie7", "", 30, ""},
            {"d3s_CAP_beanie8", "", 30, ""},
            {"d3s_CAP_beanie_1", "", 30, ""},
            {"d3s_CAP_beanie_1_a", "", 30, ""},
            {"d3s_CAP_beanie_1_b", "", 30, ""},
            {"d3s_CAP_beanie_1_c", "", 30, ""},
            {"d3s_CAP_beanie_1_d", "", 30, ""},
            {"d3s_CAP_beanie_1_e", "", 30, ""},
            {"d3s_CAP_beanie_1_f", "", 30, ""},
            {"d3s_CAP_beanie_1_g", "", 30, ""},
            {"d3s_CAP_beanie_1_h", "", 30, ""},
            {"d3s_CAP_beanie_1_i", "", 30, ""},
            {"d3s_CAP_beanie_1_j", "", 30, ""},
            {"d3s_CAP_beanie_1_k", "", 30, ""},
            {"d3s_CAP_beanie_1_l", "", 30, ""},
            {"d3s_CAP_beanie_1_m", "", 30, ""},
            {"d3s_CAP_beanie_2_a", "", 30, ""},
            {"d3s_CAP_beanie_2_b", "", 30, ""},
            {"d3s_CAP_beanie_2_c", "", 30, ""},
            {"d3s_CAP_beanie_2_d", "", 30, ""},
            {"d3s_CAP_beanie_2_e", "", 30, ""},
            {"d3s_CAP_beanie_2_f", "", 30, ""},
            {"d3s_CAP_beanie_2_g", "", 30, ""},
            {"d3s_CAP_beanie_2_h", "", 30, ""},
            {"d3s_CAP_beanie_2_i", "", 30, ""},
            {"d3s_CAP_beanie_2_j", "", 30, ""},
            {"d3s_CAP_beanie_2_k", "", 30, ""},
            {"d3s_CAP_beanie_2_l", "", 30, ""},
            {"d3s_CAP_beanie_2_m", "", 30, ""},
            {"d3s_CAP_beanie_2_n", "", 30, ""},
            {"d3s_CAP_beanie_2_o", "", 30, ""},
            {"d3s_CAP_Embacy", "", 30, ""},
            {"d3s_CAP_furcap", "", 30, ""},
            {"d3s_CAP_russelite_hat", "", 30, ""},
            {"d3s_CAP_Headgear", "", 30, ""},
            {"d3s_CAP_Headgear1", "", 30, ""},
            {"d3s_CAP_Headgear_1", "", 30, ""},
            {"d3s_CAP_Headgear1_1", "", 30, ""}
        };

        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Shades_Black", "", 20, "" },
            { "G_Shades_Blue", "", 20, "" },
            { "G_Shades_Green", "", 20, "" },
            { "G_Shades_Red", "", 20, "" },
            { "G_Sport_Blackred", "", 25, "" },
            { "G_Sport_BlackWhite", "", 25, "" },
            { "G_Sport_Blackyellow", "", 25, "" },
            { "G_Sport_Checkered", "", 25, "" },
            { "G_Sport_Greenblack", "", 25, "" },
            { "G_Sport_Red", "", 25, "" },
            { "G_Lowprofile", "", 20, "" },
            { "G_Squares", "", 20, "" },
            { "G_Aviator", "", 50, "" },
            { "G_Combat", "", 23, "" },
            { "G_Lady_Mirror", "", 26, "" },
            { "G_Lady_Dark", "", 26, "" },
            { "G_Lady_Blue", "", 26, "" },
            { "d3s_p_eyes_000_a", "", 50, "" },
            { "d3s_p_eyes_000_b", "", 50, "" },
            { "d3s_p_eyes_000_c", "", 50, "" },
            { "d3s_p_eyes_000_d", "", 50, "" },
            { "d3s_p_eyes_000_e", "", 50, "" },
            { "d3s_p_eyes_000_f", "", 50, "" },
            { "d3s_p_eyes_000_g", "", 50, "" },
            { "d3s_p_eyes_000_h", "", 50, "" },
            { "d3s_p_eyes_000_i", "", 50, "" },
            { "d3s_p_eyes_000_j", "", 50, "" },
            { "d3s_p_eyes_000_k", "", 50, "" },
            { "d3s_p_eyes_000_l", "", 50, "" },
            { "d3s_p_eyes_000_m", "", 50, "" },
            { "d3s_p_eyes_000_n", "", 50, "" },
            { "d3s_p_eyes_000_o", "", 50, "" },
            { "d3s_p_eyes_001", "", 50, "" },
            { "d3s_Glasses_scarf_a", "", 50, "" },
            { "d3s_Glasses_scarf_b", "", 50, "" },
            { "d3s_Glasses_scarf_c", "", 50, "" },
            { "d3s_Glasses_scarf1_a", "", 50, "" },
            { "d3s_Glasses_scarf1_b", "", 50, "" },
            { "d3s_Glasses_scarf1_c", "", 50, "" },
            { "d3s_Glasses_scarf1_d", "", 50, "" },
            { "d3s_Glasses_scarf2_a", "", 50, "" },
            { "d3s_Glasses_scarf2_b", "", 50, "" },
            { "d3s_Glasses_scarf2_c", "", 50, "" },
            { "d3s_Glasses_scarf2_d", "", 50, "" },
            { "d3s_Glasses_scarf2_e", "", 50, "" },
            { "d3s_Glasses_scarf2_f", "", 50, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "AL_BlackSheepVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 189" },
            { "AL_ComBlackSheepVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 189" },
            { "AL_BandidosVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 102" },
            { "AL_BrotherhoodVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 50" },
            { "AL_LosDCartelVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 179" },
            { "AL_MillersVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 64" },
            { "AL_ManarelloVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 16" },
            { "AL_UrFatVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 51" },
            { "AL_NotoriousVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 118" },
            { "AL_CrownCartelVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 136" },
            { "AL_PullUpBoysVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 152" },
            { "AL_CaponeFamilyVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 100" },
            { "AL_OuterHeavenVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 117" },
            { "AL_SyndicateVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 81" },
            { "AL_YakuzaVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 188" },
            { "AL_SonoraVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 201" },
            { "AL_SosaVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 195" },
            { "AL_VigilantesVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 36" },

            { "V_DeckCrew_brown_F", "", 200, "" },
            { "V_DeckCrew_blue_F", "", 200, "" },
            { "V_DeckCrew_white_F", "", 200, "" },
            { "V_DeckCrew_red_F", "", 200, "" },
            { "V_DeckCrew_violet_F", "", 200, "" },
            { "V_DeckCrew_white_F", "", 200, "" },
            { "V_DeckCrew_yellow_F", "", 200, "" },
            { "V_TacVest_gen_F", "", 300, "" },
            { "AL_CivHeavyVest1", "", 1300, "" },
            { "AL_CivHeavyVest2", "", 1300, "" },
            { "AL_CivHeavyVest3", "", 1300, "" },
            { "AL_CivHeavyVest4", "", 1300, "" },
            { "AL_CivHeavyVest5", "", 1300, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "travis_InvisibeCarryall", "", 300, "" },
            { "B_OutdoorPack_blk", "", 150, "" },
            { "B_AssaultPack_khk", "", 200, "" },
            { "B_AssaultPack_dgtl", "", 200, "" },
            { "B_AssaultPack_rgr", "", 200, "" },
            { "B_AssaultPack_sgg", "", 200, "" },
            { "B_AssaultPack_blk", "", 200, "" },
            { "B_AssaultPack_cbr", "", 200, "" },
            { "B_AssaultPack_mcamo", "", 200, "" },
            { "B_AssaultPack_tna_f", "", 200, "" },
            { "B_TacticalPack_oli", "", 200, "" },
            { "B_Kitbag_mcamo", "", 300, "" },
            { "B_Kitbag_sgg", "", 300, "" },
            { "B_Kitbag_cbr", "", 300, "" },
            { "B_FieldPack_blk", "", 400, "" },
            { "B_FieldPack_ocamo", "", 400, "" },
            { "B_FieldPack_oucamo", "", 400, "" },
            { "B_FieldPack_ghex_f", "", 400, "" },
            { "B_Bergen_sgg", "", 500, "" },
            { "B_Bergen_mcamo", "", 500, "" },
            { "B_Bergen_rgr", "", 500, "" },
            { "B_Bergen_blk", "", 500, "" },
            { "B_Carryall_ocamo", "", 550, "" },
            { "B_Carryall_oucamo", "", 550, "" },
            { "B_Carryall_mcamo", "", 550, "" },
            { "B_Carryall_oli", "", 550, "" },
            { "B_Carryall_khk", "", 550, "" },
            { "B_Carryall_cbr", "", 550, "" },
            { "B_Carryall_ghex_f", "", 650, "" },
            { "B_Bergen_dgtl_f", "", 650, "" },
            { "B_AssaultPack_mcamo", "", 200, "" },
            { "B_TacticalPack_oli", "", 30, "" },
            { "B_Kitbag_mcamo", "", 300, "" },
            { "B_Kitbag_sgg", "", 300, "" },
            { "B_Kitbag_cbr", "", 300, "" },
            { "B_FieldPack_blk", "", 500, "" },
            { "B_FieldPack_ocamo", "", 500, "" },
            { "B_FieldPack_oucamo", "", 500, "" },
            { "B_Bergen_sgg", "", 650, "" },
            { "B_Bergen_mcamo", "", 650, "" },
            { "B_Bergen_rgr", "", 650, "" },
            { "B_Bergen_blk", "", 650, "" },
            { "B_Carryall_ocamo", "", 750, "" },
            { "B_Carryall_oucamo", "", 750, "" },
            { "B_Carryall_mcamo", "", 750, "" },
            { "B_Carryall_oli", "", 750, "" },
            { "B_Carryall_khk", "", 750, "" },
            { "B_Carryall_cbr", "", 750, "" },
            { "casper_beautifulbackpack", "", 460, "" },
            { "casper_cockbackpack", "", 460, "" },
            { "casper_facbackpack", "", 460, "" },
            { "casper_hellokittybackpack", "", 460, "" },
            { "casper_mcdonaldsbackpack", "", 460, "" },
            { "casper_nemobackpack", "", 460, "" },
            { "casper_ppatrolbackpack", "", 460, "" },
            { "d3s_backpack", "", 800, "" },
            { "d3s_backpack_a", "", 800, "" },
            { "d3s_backpack_b", "", 800, "" },
            { "d3s_backpack_c", "", 800, "" },
            { "d3s_backpack_d", "", 800, "" },
            { "d3s_backpack_e", "", 800, "" },
            { "d3s_backpack_f", "", 800, "" },
            { "d3s_backpack_g", "", 800, "" },
            { "d3s_backpack_h", "", 800, "" },
            { "d3s_backpack_i", "", 800, "" },
            { "d3s_backpack_j", "", 800, "" },
            { "d3s_backpack_k", "", 800, "" },
            { "d3s_backpack_l", "", 800, "" },
            { "d3s_backpack_m", "", 800, "" }
        };
    };

    class cop {
        title = "STR_Shops_C_Police";
        conditions = "";
        side = "cop";
         uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },

            //DOC
            { "AL_Corrections1", "", 20, "call life_copdept in [1,5,7]" },
            { "AL_Corrections2", "", 20, "call life_copdept in [1,5,7]" },
            { "AL_Corrections3", "", 20, "call life_copdept in [1,5,7]" },
            { "AL_Corrections4", "", 20, "call life_copdept in [1,5,7]" },
            { "AL_Corrections5", "", 20, "call life_copdept in [1,5,7]" },
            { "AL_Corrections6", "", 20, "call life_copdept in [1,5,7]" },
            
            //regular police
            { "AL_Police0", "", 20, "call life_copdept in [2,6,7]" },
            { "AL_Police1", "", 20, "call life_copdept in [2,6,7]" },
            { "AL_Police2", "", 20, "call life_copdept in [2,6,7]" },
            { "AL_Police3", "", 20, "call life_copdept in [2,6,7]" },
            { "AL_Police4", "", 20, "call life_copdept in [2,6,7]" },
            { "AL_Police5", "", 20, "call life_copdept in [2,6,7]" },
            { "AL_Police6", "", 20, "call life_copdept in [2,6,7]" },
            { "AL_Police18", "", 20, "call life_copdept in [2,6,7]" },
            { "AL_Police19", "", 20, "call life_copdept in [2,6,7]" },

            //fuckknows
            { "AL_HWP1", "", 20, "call life_copdept in [3,7]" },
            { "AL_HWP2", "", 20, "call life_copdept in [3,7]" },
            
            //IA
            { "AL_IAUniform", "", 20, "call life_copdept in [4,7]" },

            //CRT
            { "AL_CRTUniform", "", 20, "call life_copdept in [5,7]" },

            //BOI
            { "AL_BOIJacketBlack", "", 20, "call life_copdept in [6,7]" },
            { "AL_BOIJacketBlue", "", 20, "call life_copdept in [6,7]" },
            { "AL_BOIJacketPurple", "", 20, "call life_copdept in [6,7]" },

            //SWAT
            { "swat_uni_black", "", 20, "call life_copdept in [6,7]" },
            { "swat_uni_mblack", "", 20, "call life_copdept in [6,7]" },
            { "swat_uni_odgreen", "", 20, "call life_copdept in [6,7]" },

            //Special
            { "AL_PoliceWetsuit", "", 20, "call life_copdept in [5,6,7]" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "AL_PoliceHat", "", 25, "" },
            { "d3s_CAP_p_head_007_1", "", 100, "call life_copdept in [5,6,7]" },
            { "d3s_CAP_p_head_007_2", "", 130, "call life_copdept in [5,6,7]" },

            //Boi
            { "AL_BOIBeret", "", 300, "call life_copdept in [6,7]" },
            { "AL_BOI_Beanie_Black", "", 300, "call life_copdept in [6,7]" },
            { "AL_BOI_Beanie_Blue", "", 300, "call life_copdept in [6,7]" },
            { "AL_BOI_Beanie_Purple", "", 300, "call life_copdept in [6,7]" },
            
            //SWAT
            { "Swat_blk_Helmet", "", 300, "call life_copdept in [6,7]" },
            { "Swat_MBLK_Helmet", "", 300, "call life_copdept in [6,7]" },
            { "Swat_OD_Helmet", "", 300, "call life_copdept in [6,7]" },
            { "SWAT_Blk_Boonie", "", 100, "call life_copdept in [6,7]" },
            { "SWAT_MBlk_Boonie", "", 100, "call life_copdept in [6,7]" },
            { "SWAT_OD_Boonie", "", 100, "call life_copdept in [6,7]" },
            { "SWAT_Beret", "", 100, "call life_copdept in [6,7]" },
            { "SWAT_Cap", "", 100, "call life_copdept in [6,7]" },
            { "SWAT_Shemagh", "", 100, "call life_copdept in [6,7]" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Shades_Black", "", 20, "" },
            { "G_Shades_Blue", "", 20, "" },
            { "G_Shades_Green", "", 20, "" },
            { "G_Shades_Red", "", 20, "" },
            { "G_Sport_Blackred", "", 25, "" },
            { "G_Sport_BlackWhite", "", 25, "" },
            { "G_Sport_Blackyellow", "", 25, "" },
            { "G_Sport_Checkered", "", 25, "" },
            { "G_Sport_Greenblack", "", 25, "" },
            { "G_Sport_Red", "", 25, "" },
            { "G_Lowprofile", "", 20, "" },
            { "G_Squares", "", 20, "" },
            { "G_Aviator", "", 50, "" },
            { "G_Combat", "", 23, "" },
            { "G_Lady_Mirror", "", 26, "" },
            { "G_Lady_Dark", "", 26, "" },
            { "G_Lady_Blue", "", 26, "" },
            { "d3s_p_eyes_000_a", "", 50, "" },
            { "d3s_p_eyes_000_b", "", 50, "" },
            { "d3s_p_eyes_000_c", "", 50, "" },
            { "d3s_p_eyes_000_d", "", 50, "" },
            { "d3s_p_eyes_000_e", "", 50, "" },
            { "d3s_p_eyes_000_f", "", 50, "" },
            { "d3s_p_eyes_000_g", "", 50, "" },
            { "d3s_p_eyes_000_h", "", 50, "" },
            { "d3s_p_eyes_000_i", "", 50, "" },
            { "d3s_p_eyes_000_j", "", 50, "" },
            { "d3s_p_eyes_000_k", "", 50, "" },
            { "d3s_p_eyes_000_l", "", 50, "" },
            { "d3s_p_eyes_000_m", "", 50, "" },
            { "d3s_p_eyes_000_n", "", 50, "" },
            { "d3s_p_eyes_000_o", "", 50, "" },
            { "d3s_p_eyes_001", "", 50, "" },
            { "G_Diving", "", 10, "call life_copdept in [5,6,7]" },
            { "G_Bandanna_blk", "", 10, "call life_copdept in [5,6,7]" },
            { "G_Balaclava_TI_blk_F", "", 40, "call life_copdept in [5,6,7]" },

            //Keenun Swat Stuff
            { "G_Bandanna_oli", "", 10, "call life_copdept in [6,7]" },
            { "G_Bandanna_blk", "", 10, "call life_copdept in [6,7]" },
            { "G_Bandanna_beast", "", 10, "call life_copdept in [6,7]" },
            { "G_Bandanna_aviator", "", 10, "call life_copdept in [6,7]" },
            { "G_Balaclava_oli", "", 10, "call life_copdept in [6,7]" },
            { "G_Balaclava_blk", "", 10, "call life_copdept in [6,7]" },
            { "TRYK_R_CAP_BLK", "", 10, "call life_copdept in [6,7]" },
            { "TRYK_R_CAP_OD_US", "", 10, "call life_copdept in [6,7]" },
            { "TRYK_SpsetG_Glasses", "", 10, "call life_copdept in [6,7]" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "travis_RideAlongVest", "", 600, "" },
            { "AL_CorrectionsHeavyVest", "", 600, "call life_copdept in [1,5,7]" },
            { "AL_PoliceHeavyVest", "", 600, "call life_copdept in [2,6,7]" },
            { "AL_HWPHeavyVest", "", 600, "call life_copdept in [3,7]" },
            { "AL_InternalAffairsHeavyVest", "", 600, "call life_copdept in [4,7]" },
            { "AL_CRTHeavyVest", "", 600, "call life_copdept in [5,7]" },
            { "AL_PoliceRebreatherHeavyVest", "", 100, "call life_copdept in [5,6,7]" },

            //BOI
            { "AL_CIDHeavyVest", "", 600, "call life_copdept in [6,7]" },

            //SWAT
            { "swat_vest_blk", "", 600, "call life_copdept in [6,7]" },
            { "swat_vest_multi_blk", "", 600, "call life_copdept in [6,7]" },
            { "swat_vest_od", "", 600, "call life_copdept in [6,7]" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "AL_PoliceBelt", "", 70, "" }
        };
    };

    class dive {
        title = "STR_Shops_C_Diving";
        conditions = "license_civ_dive";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_B_Wetsuit", "", 200, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Diving", "", 10, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_RebreatherB", "", 100, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "casper_beautifulbackpack", "", 500, "" }
        };
    };

    class cop_boat {
        title = "STR_Shops_C_Diving";
        conditions = "";
        side = "cop";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_B_Wetsuit", "", 200, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Diving", "", 10, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_RebreatherB", "", 100, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "AL_PoliceBelt", "", 200, "" }
        };
    };

    class gun_clothing {
        title = "STR_Shops_C_Gun";
        conditions = "license_civ_gun";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_Competitor", "", 20, "" },
            { "U_C_Man_casual_2_F", "", 20, "" },
            { "U_C_Poor_1", "", 20, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "H_Cap_marshal", "", 10, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_DeckCrew_brown_F", "", 200, "" },
            { "V_DeckCrew_blue_F", "", 200, "" },
            { "V_DeckCrew_white_F", "", 200, "" },
            { "V_DeckCrew_red_F", "", 200, "" },
            { "V_DeckCrew_violet_F", "", 200, "" },
            { "V_DeckCrew_white_F", "", 200, "" },
            { "V_DeckCrew_yellow_F", "", 200, "" },
            { "V_TacVest_gen_F", "", 300, "" },
            { "V_Press_F", "", 300, "" },
            { "AL_CivHeavyVest1", "", 1300, "" },
            { "AL_CivHeavyVest2", "", 1300, "" },
            { "AL_CivHeavyVest3", "", 1300, "" },
            { "AL_CivHeavyVest4", "", 1300, "" },
            { "AL_CivHeavyVest5", "", 1300, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "d3s_backpack_j", "", 100, "" },
            { "d3s_backpack_k", "", 100, "" },
            { "d3s_backpack_a", "", 100, "" },
            { "d3s_backpack_d", "", 100, "" },
            { "d3s_backpack_h", "", 100, "" }
        };
    };

    class med_clothing {
        title = "STR_MAR_EMS_Clothing_Shop";
        conditions = "";
        side = "med";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "travis_emstraineeuniform", "", 30, "" },
            { "travis_emsemtuniform", "", 30, "" },
            { "travis_emsparamedicuniform", "", 30, "" },
            { "travis_emsseniorparamedicuniform", "", 30, "" },
            { "travis_emscommanduniform", "", 30, "" },
            { "US_FireFighter_CombatUniform", "", 30, "" },
            { "US_FireFighter_CombatUniformBlack", "", 30, "" },
            { "U_I_Wetsuit", "", 100, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "H_Cap_grn", "EMT G1 Cap", 10, "" },
            { "H_Cap_blu", "EMT G2/3 Cap", 10, "" },
            { "H_Cap_red", "EMT G4/5 Cap", 10, "" },
            { "H_Cap_red", "Fire Casual", 30, "" },
            { "US_FireFighter_Helmet", "Fire PPE G1 Helmet", 10, "" },
            { "US_FireFighter_HelmetWhite", "Fire PPE G2 Helmet", 10, "" },
            { "US_FireFighter_HelmetBlack", "Fire PPE G3/4 Helmet", 10, "" },
            { "US_FireFighter_HelmetYellow", "Fire PPE G5+ Helmet", 10, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "US_FireFighter_ARI_Drager_Mask", "Fire PPE Mask", 10, "" },
            { "G_I_Diving", "S&R Diving Goggles", 10, "" },
            { "G_WirelessEarpiece_F", "Command Earpiece", 10, "" },
            { "G_Respirator_blue_F", "", 10, "" },
            { "G_Respirator_white_F", "", 10, "" },
            { "G_Respirator_yellow_F", "", 10, "" },
            { "G_Shades_Black", "", 20, "" },
            { "G_Shades_Blue", "", 20, "" },
            { "G_Shades_Green", "", 20, "" },
            { "G_Shades_Red", "", 20, "" },
            { "G_Sport_Blackred", "", 25, "" },
            { "G_Sport_BlackWhite", "", 25, "" },
            { "G_Sport_Blackyellow", "", 25, "" },
            { "G_Sport_Checkered", "", 25, "" },
            { "G_Sport_Greenblack", "", 25, "" },
            { "G_Sport_Red", "", 25, "" },
            { "G_Lowprofile", "", 20, "" },
            { "G_Squares", "", 20, "" },
            { "G_Aviator", "", 50, "" },
            { "G_Combat", "", 23, "" },
            { "G_Lady_Mirror", "", 26, "" },
            { "G_Lady_Dark", "", 26, "" },
            { "G_Lady_Blue", "", 26, "" },
            { "d3s_p_eyes_000_a", "", 50, "" },
            { "d3s_p_eyes_000_b", "", 50, "" },
            { "d3s_p_eyes_000_c", "", 50, "" },
            { "d3s_p_eyes_000_d", "", 50, "" },
            { "d3s_p_eyes_000_e", "", 50, "" },
            { "d3s_p_eyes_000_f", "", 50, "" },
            { "d3s_p_eyes_000_g", "", 50, "" },
            { "d3s_p_eyes_000_h", "", 50, "" },
            { "d3s_p_eyes_000_i", "", 50, "" },
            { "d3s_p_eyes_000_j", "", 50, "" },
            { "d3s_p_eyes_000_k", "", 50, "" },
            { "d3s_p_eyes_000_l", "", 50, "" },
            { "d3s_p_eyes_000_m", "", 50, "" },
            { "d3s_p_eyes_000_n", "", 50, "" },
            { "d3s_p_eyes_000_o", "", 50, "" },
            { "d3s_p_eyes_001", "", 50, "" },
            { "d3s_Glasses_scarf_a", "", 50, "" },
            { "d3s_Glasses_scarf_b", "", 50, "" },
            { "d3s_Glasses_scarf_c", "", 50, "" },
            { "d3s_Glasses_scarf1_a", "", 50, "" },
            { "d3s_Glasses_scarf1_b", "", 50, "" },
            { "d3s_Glasses_scarf1_c", "", 50, "" },
            { "d3s_Glasses_scarf1_d", "", 50, "" },
            { "d3s_Glasses_scarf2_a", "", 50, "" },
            { "d3s_Glasses_scarf2_b", "", 50, "" },
            { "d3s_Glasses_scarf2_c", "", 50, "" },
            { "d3s_Glasses_scarf2_d", "", 50, "" },
            { "d3s_Glasses_scarf2_e", "", 50, "" },
            { "d3s_Glasses_scarf2_f", "", 50, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_RebreatherIA", "S&R Diving Vest", 10, "" },
            { "travis_ParamedicVest", "", 10, "" },
            { "travis_EMTVest", "", 10, "" },
            { "travis_CommandVest", "", 10, "" },
            { "travis_RideAlongVest", "", 10, "" },
            { "travis_TraineeVest", "", 10, "" },
            { "travis_SARVest", "", 10, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "travis_InvisibeCarryall", "EMS Invisible Pack", 10, "" },
            { "US_FireFighter_ARI_Drager", "Fire PPE Tank", 10, "" }
        };
    };
    
    class bike {
        title = "STR_Shops_C_bike";
        conditions = "";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_C_Driver_1_black", "", 50, "" },
            { "U_C_Driver_1_blue", "", 50, "" },
            { "U_C_Driver_1_red", "", 50, "" },
            { "U_C_Driver_1_orange", "", 50, "" },
            { "U_C_Driver_1_green", "", 50, "" },
            { "U_C_Driver_1_white", "", 50, "" },
            { "U_C_Driver_1_yellow", "", 50, "" },
            { "U_C_Driver_2", "", 50, "" },
            { "U_C_Driver_1", "", 60, "" },
            { "U_C_Driver_3", "", 70, "" },
            { "U_C_Driver_4", "", 70, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "H_RacingHelmet_1_black_F", "", 100, "" },
            { "H_RacingHelmet_1_red_F", "", 100, "" },
            { "H_RacingHelmet_1_white_F", "", 100, "" },
            { "H_RacingHelmet_1_blue_F", "", 100, "" },
            { "H_RacingHelmet_1_yellow_F", "", 100, "" },
            { "H_RacingHelmet_1_green_F", "", 100, "" },
            { "H_RacingHelmet_1_F", "", 200, "" },
            { "H_RacingHelmet_2_F", "", 200, "" },
            { "H_RacingHelmet_3_F", "", 200, "" },
            { "H_RacingHelmet_4_F", "", 200, "" }
        };
    };

    class burglary {
        title = "STR_Shops_C_burglary";
        conditions = "";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "travis_polosecurity", "Fake Security", 20, "" },
            { "U_B_GEN_Soldier_F", "", 40, "" },
            { "U_B_GEN_Commander_F", "", 90, "" },
            { "U_B_Wetsuit", "", 200, "" },
            { "U_C_IDAP_Man_casual_F", "", 20, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "d3s_CAP_beanie_1", "", 20, "" },
            { "d3s_CAP_berd_003_u_o", "", 20, "" },
            { "d3s_CAP_berd_003_u_u", "", 20, "" },
            { "d3s_CAP_berd_006_u_k", "", 20, "" },
            { "d3s_CAP_Headgear", "", 20, "" },
            { "d3s_CAP_Headgear1", "", 20, "" },
            { "d3s_CAP_Headgear_1", "", 20, "" },
            { "H_Watchcap_blk", "", 20, "" },
            { "kio_skl_msk_black", "", 20, "" },
            { "kio_skl_msk_blood", "", 20, "" },
            { "H_EarProtectors_black_F", "", 20, "" },
            { "H_Construction_headset_orange_F", "", 20, "" },
            { "pop_palestino", "", 20, "" },
            { "H_RacingHelmet_4_F", "", 20, "" },
            { "H_WirelessEarpiece_F", "", 20, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Balaclava_blk", "", 10, "" },
            { "G_Bandanna_aviator", "", 10, "" },
            { "G_Bandanna_khk", "", 10, "" },
            { "G_Balaclava_TI_blk_F", "", 10, "" },
            { "G_Spectacles", "", 10, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_TacVestIR_blk", "", 300, "" },
            { "V_TacVest_blk", "", 300, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "B_AssaultPack_blk", "", 100, "" },
            { "d3s_backpack_b", "", 100, "" },
            { "d3s_backpack_a", "", 100, "" },
            { "d3s_backpack_d", "", 100, "" },
            { "d3s_backpack_j", "", 100, "" }
        };
    };
};
